/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdsIndex200Response,
  AdsShow200Response,
  InlineObject,
} from '../models/index';
import {
    AdsIndex200ResponseFromJSON,
    AdsIndex200ResponseToJSON,
    AdsShow200ResponseFromJSON,
    AdsShow200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/index';

export interface AdsIndexRequest {
    perPage?: number;
    page?: number;
    referenceType?: string;
}

export interface AdsShowRequest {
    ad: number;
}

/**
 * 
 */
export class AdsPromotionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for adsIndex without sending the request
     */
    async adsIndexRequestOpts(requestParameters: AdsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['referenceType'] != null) {
            queryParameters['reference_type'] = requestParameters['referenceType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ads`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async adsIndexRaw(requestParameters: AdsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdsIndex200Response>> {
        const requestOptions = await this.adsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async adsIndex(requestParameters: AdsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdsIndex200Response> {
        const response = await this.adsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adsShow without sending the request
     */
    async adsShowRequestOpts(requestParameters: AdsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ad'] == null) {
            throw new runtime.RequiredError(
                'ad',
                'Required parameter "ad" was null or undefined when calling adsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ads/{ad}`;
        urlPath = urlPath.replace(`{${"ad"}}`, encodeURIComponent(String(requestParameters['ad'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async adsShowRaw(requestParameters: AdsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdsShow200Response>> {
        const requestOptions = await this.adsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdsShow200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async adsShow(requestParameters: AdsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdsShow200Response> {
        const response = await this.adsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
