/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AiChat200Response,
  AiChatRequest,
  InlineObject,
  InlineObject1,
} from '../models/index';
import {
    AiChat200ResponseFromJSON,
    AiChat200ResponseToJSON,
    AiChatRequestFromJSON,
    AiChatRequestToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
} from '../models/index';

export interface AiChatOperationRequest {
    aiChatRequest: AiChatRequest;
}

/**
 * 
 */
export class AIChatbotApi extends runtime.BaseAPI {

    /**
     * Creates request options for aiChat without sending the request
     */
    async aiChatRequestOpts(requestParameters: AiChatOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['aiChatRequest'] == null) {
            throw new runtime.RequiredError(
                'aiChatRequest',
                'Required parameter "aiChatRequest" was null or undefined when calling aiChat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ai/chat`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AiChatRequestToJSON(requestParameters['aiChatRequest']),
        };
    }

    /**
     * Engage with an AI chatbot that understands context and provides tailored property recommendations.
     * AI assistant for property discovery
     */
    async aiChatRaw(requestParameters: AiChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AiChat200Response>> {
        const requestOptions = await this.aiChatRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AiChat200ResponseFromJSON(jsonValue));
    }

    /**
     * Engage with an AI chatbot that understands context and provides tailored property recommendations.
     * AI assistant for property discovery
     */
    async aiChat(requestParameters: AiChatOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AiChat200Response> {
        const response = await this.aiChatRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
