/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppInfoIndex200Response,
} from '../models/index';
import {
    AppInfoIndex200ResponseFromJSON,
    AppInfoIndex200ResponseToJSON,
} from '../models/index';

export interface AppInfoIndexRequest {
    key?: string;
}

/**
 * 
 */
export class AppInfoApi extends runtime.BaseAPI {

    /**
     * Creates request options for appInfoIndex without sending the request
     */
    async appInfoIndexRequestOpts(requestParameters: AppInfoIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['key'] != null) {
            queryParameters['key'] = requestParameters['key'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/app-info`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async appInfoIndexRaw(requestParameters: AppInfoIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AppInfoIndex200Response>> {
        const requestOptions = await this.appInfoIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppInfoIndex200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async appInfoIndex(requestParameters: AppInfoIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AppInfoIndex200Response> {
        const response = await this.appInfoIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
