/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthCompleteProfile200Response,
  AuthCompleteProfileRequest,
  AuthLogin200Response,
  AuthLogin401Response,
  AuthLogin403Response,
  AuthLoginRequest,
  AuthLogout200Response,
  AuthRequestOtp200Response,
  AuthRequestOtp403Response,
  AuthRequestOtpRequest,
  AuthVerifyOtp200Response,
  AuthVerifyOtpRequest,
  InlineObject,
  InlineObject1,
} from '../models/index';
import {
    AuthCompleteProfile200ResponseFromJSON,
    AuthCompleteProfile200ResponseToJSON,
    AuthCompleteProfileRequestFromJSON,
    AuthCompleteProfileRequestToJSON,
    AuthLogin200ResponseFromJSON,
    AuthLogin200ResponseToJSON,
    AuthLogin401ResponseFromJSON,
    AuthLogin401ResponseToJSON,
    AuthLogin403ResponseFromJSON,
    AuthLogin403ResponseToJSON,
    AuthLoginRequestFromJSON,
    AuthLoginRequestToJSON,
    AuthLogout200ResponseFromJSON,
    AuthLogout200ResponseToJSON,
    AuthRequestOtp200ResponseFromJSON,
    AuthRequestOtp200ResponseToJSON,
    AuthRequestOtp403ResponseFromJSON,
    AuthRequestOtp403ResponseToJSON,
    AuthRequestOtpRequestFromJSON,
    AuthRequestOtpRequestToJSON,
    AuthVerifyOtp200ResponseFromJSON,
    AuthVerifyOtp200ResponseToJSON,
    AuthVerifyOtpRequestFromJSON,
    AuthVerifyOtpRequestToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
} from '../models/index';

export interface AuthCompleteProfileOperationRequest {
    authCompleteProfileRequest: AuthCompleteProfileRequest;
}

export interface AuthLoginOperationRequest {
    authLoginRequest: AuthLoginRequest;
}

export interface AuthRequestOtpOperationRequest {
    authRequestOtpRequest: AuthRequestOtpRequest;
}

export interface AuthVerifyOtpOperationRequest {
    authVerifyOtpRequest: AuthVerifyOtpRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authCompleteProfile without sending the request
     */
    async authCompleteProfileRequestOpts(requestParameters: AuthCompleteProfileOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authCompleteProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'authCompleteProfileRequest',
                'Required parameter "authCompleteProfileRequest" was null or undefined when calling authCompleteProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/fill-name`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthCompleteProfileRequestToJSON(requestParameters['authCompleteProfileRequest']),
        };
    }

    /**
     */
    async authCompleteProfileRaw(requestParameters: AuthCompleteProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthCompleteProfile200Response>> {
        const requestOptions = await this.authCompleteProfileRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthCompleteProfile200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authCompleteProfile(requestParameters: AuthCompleteProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthCompleteProfile200Response> {
        const response = await this.authCompleteProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authLogin without sending the request
     */
    async authLoginRequestOpts(requestParameters: AuthLoginOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'authLoginRequest',
                'Required parameter "authLoginRequest" was null or undefined when calling authLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthLoginRequestToJSON(requestParameters['authLoginRequest']),
        };
    }

    /**
     */
    async authLoginRaw(requestParameters: AuthLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogin200Response>> {
        const requestOptions = await this.authLoginRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogin200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authLogin(requestParameters: AuthLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogin200Response> {
        const response = await this.authLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authLogout without sending the request
     */
    async authLogoutRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async authLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogout200Response>> {
        const requestOptions = await this.authLogoutRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLogout200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogout200Response> {
        const response = await this.authLogoutRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authRequestOtp without sending the request
     */
    async authRequestOtpRequestOpts(requestParameters: AuthRequestOtpOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authRequestOtpRequest'] == null) {
            throw new runtime.RequiredError(
                'authRequestOtpRequest',
                'Required parameter "authRequestOtpRequest" was null or undefined when calling authRequestOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRequestOtpRequestToJSON(requestParameters['authRequestOtpRequest']),
        };
    }

    /**
     */
    async authRequestOtpRaw(requestParameters: AuthRequestOtpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthRequestOtp200Response>> {
        const requestOptions = await this.authRequestOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthRequestOtp200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authRequestOtp(requestParameters: AuthRequestOtpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthRequestOtp200Response> {
        const response = await this.authRequestOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authVerifyOtp without sending the request
     */
    async authVerifyOtpRequestOpts(requestParameters: AuthVerifyOtpOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authVerifyOtpRequest'] == null) {
            throw new runtime.RequiredError(
                'authVerifyOtpRequest',
                'Required parameter "authVerifyOtpRequest" was null or undefined when calling authVerifyOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/valid-otp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthVerifyOtpRequestToJSON(requestParameters['authVerifyOtpRequest']),
        };
    }

    /**
     */
    async authVerifyOtpRaw(requestParameters: AuthVerifyOtpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthVerifyOtp200Response>> {
        const requestOptions = await this.authVerifyOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthVerifyOtp200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async authVerifyOtp(requestParameters: AuthVerifyOtpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthVerifyOtp200Response> {
        const response = await this.authVerifyOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
