/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatMessagesStore201Response,
  ChatMessagesStoreRequest,
  ChatSessionsIndex200Response,
  ChatSessionsStore201Response,
  ChatSessionsStoreRequest,
  InlineObject,
  ListingsReviewsDestroy200Response,
} from '../models/index';
import {
    ChatMessagesStore201ResponseFromJSON,
    ChatMessagesStore201ResponseToJSON,
    ChatMessagesStoreRequestFromJSON,
    ChatMessagesStoreRequestToJSON,
    ChatSessionsIndex200ResponseFromJSON,
    ChatSessionsIndex200ResponseToJSON,
    ChatSessionsStore201ResponseFromJSON,
    ChatSessionsStore201ResponseToJSON,
    ChatSessionsStoreRequestFromJSON,
    ChatSessionsStoreRequestToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    ListingsReviewsDestroy200ResponseFromJSON,
    ListingsReviewsDestroy200ResponseToJSON,
} from '../models/index';

export interface ChatMessagesStoreOperationRequest {
    session: number;
    chatMessagesStoreRequest: ChatMessagesStoreRequest;
}

export interface ChatSessionsDestroyRequest {
    session: number;
}

export interface ChatSessionsShowRequest {
    session: number;
}

export interface ChatSessionsStoreOperationRequest {
    chatSessionsStoreRequest?: ChatSessionsStoreRequest;
}

/**
 * 
 */
export class ChatBotApi extends runtime.BaseAPI {

    /**
     * Creates request options for chatMessagesStore without sending the request
     */
    async chatMessagesStoreRequestOpts(requestParameters: ChatMessagesStoreOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['session'] == null) {
            throw new runtime.RequiredError(
                'session',
                'Required parameter "session" was null or undefined when calling chatMessagesStore().'
            );
        }

        if (requestParameters['chatMessagesStoreRequest'] == null) {
            throw new runtime.RequiredError(
                'chatMessagesStoreRequest',
                'Required parameter "chatMessagesStoreRequest" was null or undefined when calling chatMessagesStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/sessions/{session}/messages`;
        urlPath = urlPath.replace(`{${"session"}}`, encodeURIComponent(String(requestParameters['session'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatMessagesStoreRequestToJSON(requestParameters['chatMessagesStoreRequest']),
        };
    }

    /**
     * AI can suggest properties. The response includes recommended listings with IDs for navigation.
     * Send message to AI Chatbot
     */
    async chatMessagesStoreRaw(requestParameters: ChatMessagesStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatMessagesStore201Response>> {
        const requestOptions = await this.chatMessagesStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatMessagesStore201ResponseFromJSON(jsonValue));
    }

    /**
     * AI can suggest properties. The response includes recommended listings with IDs for navigation.
     * Send message to AI Chatbot
     */
    async chatMessagesStore(requestParameters: ChatMessagesStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatMessagesStore201Response> {
        const response = await this.chatMessagesStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for chatSessionsDestroy without sending the request
     */
    async chatSessionsDestroyRequestOpts(requestParameters: ChatSessionsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['session'] == null) {
            throw new runtime.RequiredError(
                'session',
                'Required parameter "session" was null or undefined when calling chatSessionsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/sessions/{session}`;
        urlPath = urlPath.replace(`{${"session"}}`, encodeURIComponent(String(requestParameters['session'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a chat session
     */
    async chatSessionsDestroyRaw(requestParameters: ChatSessionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsReviewsDestroy200Response>> {
        const requestOptions = await this.chatSessionsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsReviewsDestroy200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a chat session
     */
    async chatSessionsDestroy(requestParameters: ChatSessionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsReviewsDestroy200Response> {
        const response = await this.chatSessionsDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for chatSessionsIndex without sending the request
     */
    async chatSessionsIndexRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/sessions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get user\'s chat sessions
     */
    async chatSessionsIndexRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatSessionsIndex200Response>> {
        const requestOptions = await this.chatSessionsIndexRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatSessionsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user\'s chat sessions
     */
    async chatSessionsIndex(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatSessionsIndex200Response> {
        const response = await this.chatSessionsIndexRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for chatSessionsShow without sending the request
     */
    async chatSessionsShowRequestOpts(requestParameters: ChatSessionsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['session'] == null) {
            throw new runtime.RequiredError(
                'session',
                'Required parameter "session" was null or undefined when calling chatSessionsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/sessions/{session}`;
        urlPath = urlPath.replace(`{${"session"}}`, encodeURIComponent(String(requestParameters['session'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get single chat session
     */
    async chatSessionsShowRaw(requestParameters: ChatSessionsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatSessionsStore201Response>> {
        const requestOptions = await this.chatSessionsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatSessionsStore201ResponseFromJSON(jsonValue));
    }

    /**
     * Get single chat session
     */
    async chatSessionsShow(requestParameters: ChatSessionsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatSessionsStore201Response> {
        const response = await this.chatSessionsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for chatSessionsStore without sending the request
     */
    async chatSessionsStoreRequestOpts(requestParameters: ChatSessionsStoreOperationRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/chat/sessions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatSessionsStoreRequestToJSON(requestParameters['chatSessionsStoreRequest']),
        };
    }

    /**
     * Create new chat session
     */
    async chatSessionsStoreRaw(requestParameters: ChatSessionsStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatSessionsStore201Response>> {
        const requestOptions = await this.chatSessionsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatSessionsStore201ResponseFromJSON(jsonValue));
    }

    /**
     * Create new chat session
     */
    async chatSessionsStore(requestParameters: ChatSessionsStoreOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatSessionsStore201Response> {
        const response = await this.chatSessionsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
