/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FeaturedListingsIndex200Response,
} from '../models/index';
import {
    FeaturedListingsIndex200ResponseFromJSON,
    FeaturedListingsIndex200ResponseToJSON,
} from '../models/index';

export interface FeaturedListingsIndexRequest {
    perPage?: number;
    page?: number;
    categoryId?: number;
}

/**
 * 
 */
export class FeaturedListingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for featuredListingsIndex without sending the request
     */
    async featuredListingsIndexRequestOpts(requestParameters: FeaturedListingsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['categoryId'] != null) {
            queryParameters['category_id'] = requestParameters['categoryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/featured-listings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async featuredListingsIndexRaw(requestParameters: FeaturedListingsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FeaturedListingsIndex200Response>> {
        const requestOptions = await this.featuredListingsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FeaturedListingsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async featuredListingsIndex(requestParameters: FeaturedListingsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FeaturedListingsIndex200Response> {
        const response = await this.featuredListingsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
