/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  PaymentsIndex200Response,
  PaymentsStore201Response,
  PaymentsStoreRequest,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    PaymentsIndex200ResponseFromJSON,
    PaymentsIndex200ResponseToJSON,
    PaymentsStore201ResponseFromJSON,
    PaymentsStore201ResponseToJSON,
    PaymentsStoreRequestFromJSON,
    PaymentsStoreRequestToJSON,
} from '../models/index';

export interface PaymentsIndexRequest {
    perPage?: number;
    page?: number;
    method?: string;
    completed?: boolean;
}

export interface PaymentsStoreOperationRequest {
    paymentsStoreRequest: PaymentsStoreRequest;
}

/**
 * 
 */
export class FinanceWalletApi extends runtime.BaseAPI {

    /**
     * Creates request options for paymentsIndex without sending the request
     */
    async paymentsIndexRequestOpts(requestParameters: PaymentsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['method'] != null) {
            queryParameters['method'] = requestParameters['method'];
        }

        if (requestParameters['completed'] != null) {
            queryParameters['completed'] = requestParameters['completed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/payments`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async paymentsIndexRaw(requestParameters: PaymentsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentsIndex200Response>> {
        const requestOptions = await this.paymentsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async paymentsIndex(requestParameters: PaymentsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentsIndex200Response> {
        const response = await this.paymentsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for paymentsStore without sending the request
     */
    async paymentsStoreRequestOpts(requestParameters: PaymentsStoreOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentsStoreRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentsStoreRequest',
                'Required parameter "paymentsStoreRequest" was null or undefined when calling paymentsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/payments`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentsStoreRequestToJSON(requestParameters['paymentsStoreRequest']),
        };
    }

    /**
     */
    async paymentsStoreRaw(requestParameters: PaymentsStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentsStore201Response>> {
        const requestOptions = await this.paymentsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentsStore201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async paymentsStore(requestParameters: PaymentsStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentsStore201Response> {
        const response = await this.paymentsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
