/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Index200Response,
  Show200Response,
} from '../models/index';
import {
    Index200ResponseFromJSON,

    Show200ResponseFromJSON,
} from '../models/index';

export interface IndexRequest {
    search?: string;
    typeId?: number;
    memberId?: number;
    rentDurationId?: number;
    wilayaId?: number;
    cityId?: number;
    categoryIds?: Array<any>;
    featureIds?: Array<any>;
    nearPlaceIds?: Array<any>;
    numberRooms?: number;
    numberPersons?: number;
    minFloor?: number;
    maxFloor?: number;
    minDuration?: number;
    isReady?: boolean;
    isNegotiable?: boolean;
    minPrice?: object;
    maxPrice?: object;
    minSurface?: object;
    maxSurface?: object;
    perPage?: number;
}

export interface ShowRequest {
    listing: number;
}

export interface ReportRequest {
    listing: number;
    report: string
}


export type Report200Response = {
    success: true;
    message: string | null;
}
export type Report401Response = {
    success: false;
    message: string 
}
export type Report422Response = {
    success: false;
    message: string 
}
export type Report404Response = {
    success: false;
    message: string | null;
}

/**
 * 
 */
export class ListingApi extends runtime.BaseAPI {

    /**
     * Creates request options for index without sending the request
     */
    async indexRequestOpts(requestParameters: IndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['typeId'] != null) {
            queryParameters['type_id'] = requestParameters['typeId'];
        }

        if (requestParameters['memberId'] != null) {
            queryParameters['member_id'] = requestParameters['memberId'];
        }

        if (requestParameters['rentDurationId'] != null) {
            queryParameters['rent_duration_id'] = requestParameters['rentDurationId'];
        }

        if (requestParameters['wilayaId'] != null) {
            queryParameters['wilaya_id'] = requestParameters['wilayaId'];
        }

        if (requestParameters['cityId'] != null) {
            queryParameters['city_id'] = requestParameters['cityId'];
        }

        if (requestParameters['categoryIds'] != null) {
            queryParameters['category_ids[]'] = requestParameters['categoryIds'];
        }

        if (requestParameters['featureIds'] != null) {
            queryParameters['feature_ids[]'] = requestParameters['featureIds'];
        }

        if (requestParameters['nearPlaceIds'] != null) {
            queryParameters['near_place_ids[]'] = requestParameters['nearPlaceIds'];
        }

        if (requestParameters['numberRooms'] != null) {
            queryParameters['number_rooms'] = requestParameters['numberRooms'];
        }

        if (requestParameters['numberPersons'] != null) {
            queryParameters['number_persons'] = requestParameters['numberPersons'];
        }

        if (requestParameters['minFloor'] != null) {
            queryParameters['min_floor'] = requestParameters['minFloor'];
        }

        if (requestParameters['maxFloor'] != null) {
            queryParameters['max_floor'] = requestParameters['maxFloor'];
        }

        if (requestParameters['minDuration'] != null) {
            queryParameters['min_duration'] = requestParameters['minDuration'];
        }

        if (requestParameters['isReady'] != null) {
            queryParameters['is_ready'] = requestParameters['isReady'];
        }

        if (requestParameters['isNegotiable'] != null) {
            queryParameters['is_negotiable'] = requestParameters['isNegotiable'];
        }

        if (requestParameters['minPrice'] != null) {
            queryParameters['min_price'] = requestParameters['minPrice'];
        }

        if (requestParameters['maxPrice'] != null) {
            queryParameters['max_price'] = requestParameters['maxPrice'];
        }

        if (requestParameters['minSurface'] != null) {
            queryParameters['min_surface'] = requestParameters['minSurface'];
        }

        if (requestParameters['maxSurface'] != null) {
            queryParameters['max_surface'] = requestParameters['maxSurface'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async indexRaw(requestParameters: IndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Index200Response>> {
        const requestOptions = await this.indexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Index200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async index(requestParameters: IndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Index200Response> {
        const response = await this.indexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for show without sending the request
     */
    async showRequestOpts(requestParameters: ShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling show().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings/{listing}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async showRaw(requestParameters: ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Show200Response>> {
        const requestOptions = await this.showRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Show200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async show(requestParameters: ShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Show200Response> {
        const response = await this.showRaw(requestParameters, initOverrides);
        return await response.value();
    }

    async reportRequestOpts(requestParameters: ReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling report().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings/{listing}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            body: {
                report : requestParameters["report"]
            }
        };
    }

    /**
     */
    async reportRaw(requestParameters: ReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Report200Response>> {
        const requestOptions = await this.reportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => {
            if (jsonValue == null) return jsonValue
            else return jsonValue
        });
    }

    /**
     */
    async report(requestParameters: ReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Report200Response> {
        const response = await this.reportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
