/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  ListingsBoostRequest,
  SubscriptionsCheckout200Response,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    ListingsBoostRequestFromJSON,
    ListingsBoostRequestToJSON,
    SubscriptionsCheckout200ResponseFromJSON,
    SubscriptionsCheckout200ResponseToJSON,
} from '../models/index';

export interface ListingsBoostOperationRequest {
    listing: number;
    listingsBoostRequest: ListingsBoostRequest;
}

/**
 * 
 */
export class ListingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listingsBoost without sending the request
     */
    async listingsBoostRequestOpts(requestParameters: ListingsBoostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsBoost().'
            );
        }

        if (requestParameters['listingsBoostRequest'] == null) {
            throw new runtime.RequiredError(
                'listingsBoostRequest',
                'Required parameter "listingsBoostRequest" was null or undefined when calling listingsBoost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/listings/{listing}/boost`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListingsBoostRequestToJSON(requestParameters['listingsBoostRequest']),
        };
    }

    /**
     */
    async listingsBoostRaw(requestParameters: ListingsBoostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionsCheckout200Response>> {
        const requestOptions = await this.listingsBoostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionsCheckout200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsBoost(requestParameters: ListingsBoostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionsCheckout200Response> {
        const response = await this.listingsBoostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
