/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Index200Response,
  InlineObject,
  InlineObject1,
  PasswordResetRequestResetOtp403Response,
  Show200Response,
  StoreRequestLocation,
  UpdateRequest,
} from '../models/index';
import {
    Index200ResponseFromJSON,
    Index200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    PasswordResetRequestResetOtp403ResponseFromJSON,
    PasswordResetRequestResetOtp403ResponseToJSON,
    Show200ResponseFromJSON,
    Show200ResponseToJSON,
    StoreRequestLocationFromJSON,
    StoreRequestLocationToJSON,
    UpdateRequestFromJSON,
    UpdateRequestToJSON,
} from '../models/index';

export interface ListingsDestroyRequest {
    listing: number;
}

export interface ListingsIndexRequest {
    typeId?: number;
    wilayaId?: number;
    categoryIds?: Array<any>;
    numberRooms?: number;
    isReady?: boolean;
    isNegotiable?: boolean;
    perPage?: number;
}

export interface ListingsShowRequest {
    listing: number;
}

export interface ListingsStoreRequest {
    title: string;
    price: number;
    surface: number;
    mainImage: Blob;
    rentDurationId: number;
    typeId: number;
    location: StoreRequestLocation;
    description?: string | null;
    floor?: number | null;
    boostLevel?: number | null;
    minDuration?: number | null;
    numberRooms?: number | null;
    numberPersons?: number | null;
    isReady?: boolean;
    isNegotiable?: boolean;
    categories?: Array<number> | null;
    features?: Array<number> | null;
    nearPlaces?: Array<number> | null;
    images?: Array<Blob> | null;
}

export interface ListingsUpdateRequest {
    listing: number;
    updateRequest?: UpdateRequest;
}

/**
 * 
 */
export class MemberListingsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listingsDestroy without sending the request
     */
    async listingsDestroyRequestOpts(requestParameters: ListingsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/listings/{listing}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listingsDestroyRaw(requestParameters: ListingsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasswordResetRequestResetOtp403Response>> {
        const requestOptions = await this.listingsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasswordResetRequestResetOtp403ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsDestroy(requestParameters: ListingsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasswordResetRequestResetOtp403Response> {
        const response = await this.listingsDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsIndex without sending the request
     */
    async listingsIndexRequestOpts(requestParameters: ListingsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['typeId'] != null) {
            queryParameters['type_id'] = requestParameters['typeId'];
        }

        if (requestParameters['wilayaId'] != null) {
            queryParameters['wilaya_id'] = requestParameters['wilayaId'];
        }

        if (requestParameters['categoryIds'] != null) {
            queryParameters['category_ids[]'] = requestParameters['categoryIds'];
        }

        if (requestParameters['numberRooms'] != null) {
            queryParameters['number_rooms'] = requestParameters['numberRooms'];
        }

        if (requestParameters['isReady'] != null) {
            queryParameters['is_ready'] = requestParameters['isReady'];
        }

        if (requestParameters['isNegotiable'] != null) {
            queryParameters['is_negotiable'] = requestParameters['isNegotiable'];
        }

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/listings`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listingsIndexRaw(requestParameters: ListingsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Index200Response>> {
        const requestOptions = await this.listingsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Index200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsIndex(requestParameters: ListingsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Index200Response> {
        const response = await this.listingsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsShow without sending the request
     */
    async listingsShowRequestOpts(requestParameters: ListingsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/listings/{listing}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async listingsShowRaw(requestParameters: ListingsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Show200Response>> {
        const requestOptions = await this.listingsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Show200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsShow(requestParameters: ListingsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Show200Response> {
        const response = await this.listingsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsStore without sending the request
     */
    async listingsStoreRequestOpts(requestParameters: ListingsStoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['title'] == null) {
            throw new runtime.RequiredError(
                'title',
                'Required parameter "title" was null or undefined when calling listingsStore().'
            );
        }

        if (requestParameters['price'] == null) {
            throw new runtime.RequiredError(
                'price',
                'Required parameter "price" was null or undefined when calling listingsStore().'
            );
        }

        if (requestParameters['surface'] == null) {
            throw new runtime.RequiredError(
                'surface',
                'Required parameter "surface" was null or undefined when calling listingsStore().'
            );
        }

        if (requestParameters['mainImage'] == null) {
            throw new runtime.RequiredError(
                'mainImage',
                'Required parameter "mainImage" was null or undefined when calling listingsStore().'
            );
        }

        if (requestParameters['rentDurationId'] == null) {
            throw new runtime.RequiredError(
                'rentDurationId',
                'Required parameter "rentDurationId" was null or undefined when calling listingsStore().'
            );
        }

        if (requestParameters['typeId'] == null) {
            throw new runtime.RequiredError(
                'typeId',
                'Required parameter "typeId" was null or undefined when calling listingsStore().'
            );
        }

        if (requestParameters['location'] == null) {
            throw new runtime.RequiredError(
                'location',
                'Required parameter "location" was null or undefined when calling listingsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['title'] != null) {
            formParams.append('title', requestParameters['title'] as any);
        }

        if (requestParameters['description'] != null) {
            formParams.append('description', requestParameters['description'] as any);
        }

        if (requestParameters['price'] != null) {
            formParams.append('price', requestParameters['price'] as any);
        }

        if (requestParameters['floor'] != null) {
            formParams.append('floor', requestParameters['floor'] as any);
        }

        if (requestParameters['surface'] != null) {
            formParams.append('surface', requestParameters['surface'] as any);
        }

        if (requestParameters['boostLevel'] != null) {
            formParams.append('boost_level', requestParameters['boostLevel'] as any);
        }

        if (requestParameters['minDuration'] != null) {
            formParams.append('min_duration', requestParameters['minDuration'] as any);
        }

        if (requestParameters['numberRooms'] != null) {
            formParams.append('number_rooms', requestParameters['numberRooms'] as any);
        }

        if (requestParameters['numberPersons'] != null) {
            formParams.append('number_persons', requestParameters['numberPersons'] as any);
        }

        if (requestParameters['isReady'] != null) {
            formParams.append('is_ready', requestParameters['isReady'] as any);
        }

        if (requestParameters['isNegotiable'] != null) {
            formParams.append('is_negotiable', requestParameters['isNegotiable'] as any);
        }

        if (requestParameters['mainImage'] != null) {
            formParams.append('main_image', requestParameters['mainImage'] as any);
        }

        if (requestParameters['rentDurationId'] != null) {
            formParams.append('rent_duration_id', requestParameters['rentDurationId'] as any);
        }

        if (requestParameters['typeId'] != null) {
            formParams.append('type_id', requestParameters['typeId'] as any);
        }

        if (requestParameters['location'] != null) {
            formParams.append('location', new Blob([JSON.stringify(StoreRequestLocationToJSON(requestParameters['location']))], { type: "application/json", }));
                    }

        if (requestParameters['categories'] != null) {
            formParams.append('categories', requestParameters['categories']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['features'] != null) {
            formParams.append('features', requestParameters['features']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['nearPlaces'] != null) {
            formParams.append('near_places', requestParameters['nearPlaces']!.join(runtime.COLLECTION_FORMATS["csv"]));
        }

        if (requestParameters['images'] != null) {
            requestParameters['images'].forEach((element) => {
                formParams.append('images', element as any);
            })
        }


        let urlPath = `/members/listings`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async listingsStoreRaw(requestParameters: ListingsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Show200Response>> {
        const requestOptions = await this.listingsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Show200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsStore(requestParameters: ListingsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Show200Response> {
        const response = await this.listingsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsUpdate without sending the request
     */
    async listingsUpdateRequestOpts(requestParameters: ListingsUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/members/listings/{listing}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRequestToJSON(requestParameters['updateRequest']),
        };
    }

    /**
     */
    async listingsUpdateRaw(requestParameters: ListingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Show200Response>> {
        const requestOptions = await this.listingsUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Show200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async listingsUpdate(requestParameters: ListingsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Show200Response> {
        const response = await this.listingsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
