/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Index200Response,
  InlineObject,
  MembersShow200Response,
} from '../models/index';
import {
    Index200ResponseFromJSON,
    Index200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    MembersShow200ResponseFromJSON,
    MembersShow200ResponseToJSON,
} from '../models/index';

export interface MembersListingsRequest {
    member: number;
    perPage?: number;
    page?: number;
}

export interface MembersShowRequest {
    member: number;
}

/**
 * 
 */
export class MembersApi extends runtime.BaseAPI {

    /**
     * Creates request options for membersListings without sending the request
     */
    async membersListingsRequestOpts(requestParameters: MembersListingsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['member'] == null) {
            throw new runtime.RequiredError(
                'member',
                'Required parameter "member" was null or undefined when calling membersListings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['per_page'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/{member}/listings`;
        urlPath = urlPath.replace(`{${"member"}}`, encodeURIComponent(String(requestParameters['member'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async membersListingsRaw(requestParameters: MembersListingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Index200Response>> {
        const requestOptions = await this.membersListingsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Index200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async membersListings(requestParameters: MembersListingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Index200Response> {
        const response = await this.membersListingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for membersShow without sending the request
     */
    async membersShowRequestOpts(requestParameters: MembersShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['member'] == null) {
            throw new runtime.RequiredError(
                'member',
                'Required parameter "member" was null or undefined when calling membersShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/{member}`;
        urlPath = urlPath.replace(`{${"member"}}`, encodeURIComponent(String(requestParameters['member'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async membersShowRaw(requestParameters: MembersShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MembersShow200Response>> {
        const requestOptions = await this.membersShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MembersShow200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async membersShow(requestParameters: MembersShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MembersShow200Response> {
        const response = await this.membersShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
