/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Index200Response,
  InlineObject,
  InlineObject1,
  PasswordResetRequestResetOtp403Response,
  RequestsStore201Response,
  StoreRequestRequest,
  UpdateRequestRequest,
} from '../models/index';
import {
    Index200ResponseFromJSON,
    Index200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    PasswordResetRequestResetOtp403ResponseFromJSON,
    PasswordResetRequestResetOtp403ResponseToJSON,
    RequestsStore201ResponseFromJSON,
    RequestsStore201ResponseToJSON,
    StoreRequestRequestFromJSON,
    StoreRequestRequestToJSON,
    UpdateRequestRequestFromJSON,
    UpdateRequestRequestToJSON,
} from '../models/index';

export interface RequestsDestroyRequest {
    request: number;
}

export interface RequestsIndexRequest {
    typeId?: number;
    wilayaId?: number;
    categoryIds?: Array<any>;
    numberRooms?: number;
    isReady?: boolean;
    isNegotiable?: boolean;
}

export interface RequestsShowRequest {
    request: number;
}

export interface RequestsStoreRequest {
    storeRequestRequest: StoreRequestRequest;
}

export interface RequestsUpdateRequest {
    request: number;
    updateRequestRequest?: UpdateRequestRequest;
}

/**
 * 
 */
export class MemberRequestsApi extends runtime.BaseAPI {

    /**
     * Creates request options for requestsDestroy without sending the request
     */
    async requestsDestroyRequestOpts(requestParameters: RequestsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling requestsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/requests/{request}`;
        urlPath = urlPath.replace(`{${"request"}}`, encodeURIComponent(String(requestParameters['request'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async requestsDestroyRaw(requestParameters: RequestsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasswordResetRequestResetOtp403Response>> {
        const requestOptions = await this.requestsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasswordResetRequestResetOtp403ResponseFromJSON(jsonValue));
    }

    /**
     */
    async requestsDestroy(requestParameters: RequestsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasswordResetRequestResetOtp403Response> {
        const response = await this.requestsDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestsIndex without sending the request
     */
    async requestsIndexRequestOpts(requestParameters: RequestsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['typeId'] != null) {
            queryParameters['type_id'] = requestParameters['typeId'];
        }

        if (requestParameters['wilayaId'] != null) {
            queryParameters['wilaya_id'] = requestParameters['wilayaId'];
        }

        if (requestParameters['categoryIds'] != null) {
            queryParameters['category_ids[]'] = requestParameters['categoryIds'];
        }

        if (requestParameters['numberRooms'] != null) {
            queryParameters['number_rooms'] = requestParameters['numberRooms'];
        }

        if (requestParameters['isReady'] != null) {
            queryParameters['is_ready'] = requestParameters['isReady'];
        }

        if (requestParameters['isNegotiable'] != null) {
            queryParameters['is_negotiable'] = requestParameters['isNegotiable'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/requests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async requestsIndexRaw(requestParameters: RequestsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Index200Response>> {
        const requestOptions = await this.requestsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Index200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async requestsIndex(requestParameters: RequestsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Index200Response> {
        const response = await this.requestsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestsShow without sending the request
     */
    async requestsShowRequestOpts(requestParameters: RequestsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling requestsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/requests/{request}`;
        urlPath = urlPath.replace(`{${"request"}}`, encodeURIComponent(String(requestParameters['request'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async requestsShowRaw(requestParameters: RequestsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestsStore201Response>> {
        const requestOptions = await this.requestsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestsStore201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async requestsShow(requestParameters: RequestsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestsStore201Response> {
        const response = await this.requestsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestsStore without sending the request
     */
    async requestsStoreRequestOpts(requestParameters: RequestsStoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['storeRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'storeRequestRequest',
                'Required parameter "storeRequestRequest" was null or undefined when calling requestsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/members/requests`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreRequestRequestToJSON(requestParameters['storeRequestRequest']),
        };
    }

    /**
     */
    async requestsStoreRaw(requestParameters: RequestsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestsStore201Response>> {
        const requestOptions = await this.requestsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestsStore201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async requestsStore(requestParameters: RequestsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestsStore201Response> {
        const response = await this.requestsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestsUpdate without sending the request
     */
    async requestsUpdateRequestOpts(requestParameters: RequestsUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling requestsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/members/requests/{request}`;
        urlPath = urlPath.replace(`{${"request"}}`, encodeURIComponent(String(requestParameters['request'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateRequestRequestToJSON(requestParameters['updateRequestRequest']),
        };
    }

    /**
     */
    async requestsUpdateRaw(requestParameters: RequestsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestsStore201Response>> {
        const requestOptions = await this.requestsUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestsStore201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async requestsUpdate(requestParameters: RequestsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestsStore201Response> {
        const response = await this.requestsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
