/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  ListingsReviewsDestroy200Response,
  NotificationsIndex200Response,
  ReportsStore200Response,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    ListingsReviewsDestroy200ResponseFromJSON,
    ListingsReviewsDestroy200ResponseToJSON,
    NotificationsIndex200ResponseFromJSON,
    NotificationsIndex200ResponseToJSON,
    ReportsStore200ResponseFromJSON,
    ReportsStore200ResponseToJSON,
} from '../models/index';

export interface NotificationsIndexRequest {
    page?: number;
}

export interface NotificationsMarkAsReadRequest {
    id: string;
}

export interface NotificationsMarkReadRequest {
    notification: number;
}

/**
 * 
 */
export class NotificationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for notificationsIndex without sending the request
     */
    async notificationsIndexRequestOpts(requestParameters: NotificationsIndexRequest = {}): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns notifications including action details for navigation (e.g., go to listing when clicked)
     * Get all user notifications
     */
    async notificationsIndexRaw(requestParameters: NotificationsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NotificationsIndex200Response>> {
        const requestOptions = await this.notificationsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NotificationsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns notifications including action details for navigation (e.g., go to listing when clicked)
     * Get all user notifications
     */
    async getNotifications(requestParameters: NotificationsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NotificationsIndex200Response> {
        const response = await this.notificationsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for notificationsMarkAllRead without sending the request
     */
    async notificationsMarkAllReadRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/read-all`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark all notifications as read
     */
    async notificationsMarkAllReadRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsReviewsDestroy200Response>> {
        const requestOptions = await this.notificationsMarkAllReadRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsReviewsDestroy200ResponseFromJSON(jsonValue));
    }

    /**
     * Mark all notifications as read
     */
    async notificationsMarkAllRead(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsReviewsDestroy200Response> {
        const response = await this.notificationsMarkAllReadRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for notificationsMarkAsRead without sending the request
     */
    async notificationsMarkAsReadRequestOpts(requestParameters: NotificationsMarkAsReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling notificationsMarkAsRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/{id}/read`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async notificationsMarkAsReadRaw(requestParameters: NotificationsMarkAsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReportsStore200Response>> {
        const requestOptions = await this.notificationsMarkAsReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportsStore200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async notificationsMarkAsRead(requestParameters: NotificationsMarkAsReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReportsStore200Response> {
        const response = await this.notificationsMarkAsReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for notificationsMarkRead without sending the request
     */
    async notificationsMarkReadRequestOpts(requestParameters: NotificationsMarkReadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['notification'] == null) {
            throw new runtime.RequiredError(
                'notification',
                'Required parameter "notification" was null or undefined when calling notificationsMarkRead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/notifications/{notification}/read`;
        urlPath = urlPath.replace(`{${"notification"}}`, encodeURIComponent(String(requestParameters['notification'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Mark a notification as read
     */
    async notificationsMarkReadRaw(requestParameters: NotificationsMarkReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsReviewsDestroy200Response>> {
        const requestOptions = await this.notificationsMarkReadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsReviewsDestroy200ResponseFromJSON(jsonValue));
    }

    /**
     * Mark a notification as read
     */
    async notificationsMarkRead(requestParameters: NotificationsMarkReadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsReviewsDestroy200Response> {
        const response = await this.notificationsMarkReadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
