/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthVerifyOtpRequest,
  InlineObject,
  InlineObject1,
  PasswordResetRequestResetOtp200Response,
  PasswordResetRequestResetOtp403Response,
  PasswordResetRequestResetOtpRequest,
  PasswordResetStoreNewPassword403Response,
  PasswordResetStoreNewPasswordRequest,
  PasswordResetVerifyReset200Response,
} from '../models/index';
import {
    AuthVerifyOtpRequestFromJSON,
    AuthVerifyOtpRequestToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    PasswordResetRequestResetOtp200ResponseFromJSON,
    PasswordResetRequestResetOtp200ResponseToJSON,
    PasswordResetRequestResetOtp403ResponseFromJSON,
    PasswordResetRequestResetOtp403ResponseToJSON,
    PasswordResetRequestResetOtpRequestFromJSON,
    PasswordResetRequestResetOtpRequestToJSON,
    PasswordResetStoreNewPassword403ResponseFromJSON,
    PasswordResetStoreNewPassword403ResponseToJSON,
    PasswordResetStoreNewPasswordRequestFromJSON,
    PasswordResetStoreNewPasswordRequestToJSON,
    PasswordResetVerifyReset200ResponseFromJSON,
    PasswordResetVerifyReset200ResponseToJSON,
} from '../models/index';

export interface PasswordResetRequestResetOtpOperationRequest {
    passwordResetRequestResetOtpRequest: PasswordResetRequestResetOtpRequest;
}

export interface PasswordResetStoreNewPasswordOperationRequest {
    passwordResetStoreNewPasswordRequest: PasswordResetStoreNewPasswordRequest;
}

export interface PasswordResetVerifyResetRequest {
    authVerifyOtpRequest: AuthVerifyOtpRequest;
}

/**
 * 
 */
export class PasswordResetApi extends runtime.BaseAPI {

    /**
     * Creates request options for passwordResetRequestResetOtp without sending the request
     */
    async passwordResetRequestResetOtpRequestOpts(requestParameters: PasswordResetRequestResetOtpOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passwordResetRequestResetOtpRequest'] == null) {
            throw new runtime.RequiredError(
                'passwordResetRequestResetOtpRequest',
                'Required parameter "passwordResetRequestResetOtpRequest" was null or undefined when calling passwordResetRequestResetOtp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password/request-otp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordResetRequestResetOtpRequestToJSON(requestParameters['passwordResetRequestResetOtpRequest']),
        };
    }

    /**
     * Step 1: Request OTP for Password Reset
     */
    async passwordResetRequestResetOtpRaw(requestParameters: PasswordResetRequestResetOtpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasswordResetRequestResetOtp200Response>> {
        const requestOptions = await this.passwordResetRequestResetOtpRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasswordResetRequestResetOtp200ResponseFromJSON(jsonValue));
    }

    /**
     * Step 1: Request OTP for Password Reset
     */
    async passwordResetRequestResetOtp(requestParameters: PasswordResetRequestResetOtpOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasswordResetRequestResetOtp200Response> {
        const response = await this.passwordResetRequestResetOtpRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passwordResetStoreNewPassword without sending the request
     */
    async passwordResetStoreNewPasswordRequestOpts(requestParameters: PasswordResetStoreNewPasswordOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['passwordResetStoreNewPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'passwordResetStoreNewPasswordRequest',
                'Required parameter "passwordResetStoreNewPasswordRequest" was null or undefined when calling passwordResetStoreNewPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password/store`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PasswordResetStoreNewPasswordRequestToJSON(requestParameters['passwordResetStoreNewPasswordRequest']),
        };
    }

    /**
     * Step 3: Set New Password (Authenticated via Token)
     */
    async passwordResetStoreNewPasswordRaw(requestParameters: PasswordResetStoreNewPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasswordResetRequestResetOtp403Response>> {
        const requestOptions = await this.passwordResetStoreNewPasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasswordResetRequestResetOtp403ResponseFromJSON(jsonValue));
    }

    /**
     * Step 3: Set New Password (Authenticated via Token)
     */
    async passwordResetStoreNewPassword(requestParameters: PasswordResetStoreNewPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasswordResetRequestResetOtp403Response> {
        const response = await this.passwordResetStoreNewPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for passwordResetVerifyReset without sending the request
     */
    async passwordResetVerifyResetRequestOpts(requestParameters: PasswordResetVerifyResetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authVerifyOtpRequest'] == null) {
            throw new runtime.RequiredError(
                'authVerifyOtpRequest',
                'Required parameter "authVerifyOtpRequest" was null or undefined when calling passwordResetVerifyReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password/verify-otp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthVerifyOtpRequestToJSON(requestParameters['authVerifyOtpRequest']),
        };
    }

    /**
     * Step 2: Verify OTP and provide access token
     */
    async passwordResetVerifyResetRaw(requestParameters: PasswordResetVerifyResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasswordResetVerifyReset200Response>> {
        const requestOptions = await this.passwordResetVerifyResetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasswordResetVerifyReset200ResponseFromJSON(jsonValue));
    }

    /**
     * Step 2: Verify OTP and provide access token
     */
    async passwordResetVerifyReset(requestParameters: PasswordResetVerifyResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasswordResetVerifyReset200Response> {
        const response = await this.passwordResetVerifyResetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
