/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  PasswordResetRequestResetOtp403Response,
  ProfileShow200Response,
  ProfileUpdate200Response,
  UpdatePasswordRequest,
  UpdateProfileRequest,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    PasswordResetRequestResetOtp403ResponseFromJSON,
    PasswordResetRequestResetOtp403ResponseToJSON,
    ProfileShow200ResponseFromJSON,
    ProfileShow200ResponseToJSON,
    ProfileUpdate200ResponseFromJSON,
    ProfileUpdate200ResponseToJSON,
    UpdatePasswordRequestFromJSON,
    UpdatePasswordRequestToJSON,
    UpdateProfileRequestFromJSON,
    UpdateProfileRequestToJSON,
} from '../models/index';

export interface ProfileUpdateRequest {
    updateProfileRequest: UpdateProfileRequest;
}

export interface ProfileUpdateImageRequest {
    profileImage: Blob;
}

export interface ProfileUpdatePasswordRequest {
    updatePasswordRequest: UpdatePasswordRequest;
}

export interface ProfileVerifyAgentRequest {
    document: Blob;
}

export interface ProfileVerifyMemberRequest {
    cardIdFront: Blob;
    cardIdBack: Blob;
}

/**
 * 
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     * Creates request options for profileShow without sending the request
     */
    async profileShowRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/members/profile`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async profileShowRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileShow200Response>> {
        const requestOptions = await this.profileShowRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileShow200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async profileShow(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileShow200Response> {
        const response = await this.profileShowRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileUpdate without sending the request
     */
    async profileUpdateRequestOpts(requestParameters: ProfileUpdateRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProfileRequest',
                'Required parameter "updateProfileRequest" was null or undefined when calling profileUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/members/profile`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProfileRequestToJSON(requestParameters['updateProfileRequest']),
        };
    }

    /**
     */
    async profileUpdateRaw(requestParameters: ProfileUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileUpdate200Response>> {
        const requestOptions = await this.profileUpdateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileUpdate200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async profileUpdate(requestParameters: ProfileUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileUpdate200Response> {
        const response = await this.profileUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileUpdateImage without sending the request
     */
    async profileUpdateImageRequestOpts(requestParameters: ProfileUpdateImageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['profileImage'] == null) {
            throw new runtime.RequiredError(
                'profileImage',
                'Required parameter "profileImage" was null or undefined when calling profileUpdateImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['profileImage'] != null) {
            formParams.append('profile_image', requestParameters['profileImage'] as any);
        }


        let urlPath = `/members/profile/image`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async profileUpdateImageRaw(requestParameters: ProfileUpdateImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileUpdate200Response>> {
        const requestOptions = await this.profileUpdateImageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileUpdate200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async profileUpdateImage(requestParameters: ProfileUpdateImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileUpdate200Response> {
        const response = await this.profileUpdateImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileUpdatePassword without sending the request
     */
    async profileUpdatePasswordRequestOpts(requestParameters: ProfileUpdatePasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updatePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePasswordRequest',
                'Required parameter "updatePasswordRequest" was null or undefined when calling profileUpdatePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/members/profile/password`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePasswordRequestToJSON(requestParameters['updatePasswordRequest']),
        };
    }

    /**
     */
    async profileUpdatePasswordRaw(requestParameters: ProfileUpdatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileUpdate200Response>> {
        const requestOptions = await this.profileUpdatePasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileUpdate200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async profileUpdatePassword(requestParameters: ProfileUpdatePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileUpdate200Response> {
        const response = await this.profileUpdatePasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileVerifyAgent without sending the request
     */
    async profileVerifyAgentRequestOpts(requestParameters: ProfileVerifyAgentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['document'] == null) {
            throw new runtime.RequiredError(
                'document',
                'Required parameter "document" was null or undefined when calling profileVerifyAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['document'] != null) {
            formParams.append('document', requestParameters['document'] as any);
        }


        let urlPath = `/members/profile/verify-agent`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async profileVerifyAgentRaw(requestParameters: ProfileVerifyAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileUpdate200Response>> {
        const requestOptions = await this.profileVerifyAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileUpdate200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async profileVerifyAgent(requestParameters: ProfileVerifyAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileUpdate200Response> {
        const response = await this.profileVerifyAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for profileVerifyMember without sending the request
     */
    async profileVerifyMemberRequestOpts(requestParameters: ProfileVerifyMemberRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['cardIdFront'] == null) {
            throw new runtime.RequiredError(
                'cardIdFront',
                'Required parameter "cardIdFront" was null or undefined when calling profileVerifyMember().'
            );
        }

        if (requestParameters['cardIdBack'] == null) {
            throw new runtime.RequiredError(
                'cardIdBack',
                'Required parameter "cardIdBack" was null or undefined when calling profileVerifyMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['cardIdFront'] != null) {
            formParams.append('card_id_front', requestParameters['cardIdFront'] as any);
        }

        if (requestParameters['cardIdBack'] != null) {
            formParams.append('card_id_back', requestParameters['cardIdBack'] as any);
        }


        let urlPath = `/members/profile/verify-member`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async profileVerifyMemberRaw(requestParameters: ProfileVerifyMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileUpdate200Response>> {
        const requestOptions = await this.profileVerifyMemberRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileUpdate200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async profileVerifyMember(requestParameters: ProfileVerifyMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileUpdate200Response> {
        const response = await this.profileVerifyMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
