/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  PropertyMatchersIndex200Response,
  PropertyMatchersStore201Response,
  PropertyMatchersStoreRequest,
  ReportsStore200Response,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    PropertyMatchersIndex200ResponseFromJSON,
    PropertyMatchersIndex200ResponseToJSON,
    PropertyMatchersStore201ResponseFromJSON,
    PropertyMatchersStore201ResponseToJSON,
    PropertyMatchersStoreRequestFromJSON,
    PropertyMatchersStoreRequestToJSON,
    ReportsStore200ResponseFromJSON,
    ReportsStore200ResponseToJSON,
} from '../models/index';

export interface PropertyMatchersDestroyRequest {
    propertyMatcher: number;
}

export interface PropertyMatchersStoreOperationRequest {
    propertyMatchersStoreRequest: PropertyMatchersStoreRequest;
}

/**
 * 
 */
export class PropertyMatcherApi extends runtime.BaseAPI {

    /**
     * Creates request options for propertyMatchersDestroy without sending the request
     */
    async propertyMatchersDestroyRequestOpts(requestParameters: PropertyMatchersDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyMatcher'] == null) {
            throw new runtime.RequiredError(
                'propertyMatcher',
                'Required parameter "propertyMatcher" was null or undefined when calling propertyMatchersDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/property-matchers/{propertyMatcher}`;
        urlPath = urlPath.replace(`{${"propertyMatcher"}}`, encodeURIComponent(String(requestParameters['propertyMatcher'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async propertyMatchersDestroyRaw(requestParameters: PropertyMatchersDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReportsStore200Response>> {
        const requestOptions = await this.propertyMatchersDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportsStore200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async propertyMatchersDestroy(requestParameters: PropertyMatchersDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReportsStore200Response> {
        const response = await this.propertyMatchersDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for propertyMatchersIndex without sending the request
     */
    async propertyMatchersIndexRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/property-matchers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async propertyMatchersIndexRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyMatchersIndex200Response>> {
        const requestOptions = await this.propertyMatchersIndexRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PropertyMatchersIndex200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async propertyMatchersIndex(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyMatchersIndex200Response> {
        const response = await this.propertyMatchersIndexRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for propertyMatchersStore without sending the request
     */
    async propertyMatchersStoreRequestOpts(requestParameters: PropertyMatchersStoreOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['propertyMatchersStoreRequest'] == null) {
            throw new runtime.RequiredError(
                'propertyMatchersStoreRequest',
                'Required parameter "propertyMatchersStoreRequest" was null or undefined when calling propertyMatchersStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/property-matchers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PropertyMatchersStoreRequestToJSON(requestParameters['propertyMatchersStoreRequest']),
        };
    }

    /**
     * Save search criteria to receive automated notifications when matching properties are listed.
     * Create a smart search alert
     */
    async propertyMatchersStoreRaw(requestParameters: PropertyMatchersStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PropertyMatchersStore201Response>> {
        const requestOptions = await this.propertyMatchersStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PropertyMatchersStore201ResponseFromJSON(jsonValue));
    }

    /**
     * Save search criteria to receive automated notifications when matching properties are listed.
     * Create a smart search alert
     */
    async propertyMatchersStore(requestParameters: PropertyMatchersStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PropertyMatchersStore201Response> {
        const response = await this.propertyMatchersStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
