/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  ReportsStore200Response,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    ReportsStore200ResponseFromJSON,
    ReportsStore200ResponseToJSON,
} from '../models/index';

export interface ReportsStoreRequest {
    reportableType: ReportsStoreReportableTypeEnum;
    reportableId: number;
    reason: ReportsStoreReasonEnum;
    description?: string;
    evidenceImages?: Array<Blob>;
}

/**
 * 
 */
export class ReportsApi extends runtime.BaseAPI {

    /**
     * Creates request options for reportsStore without sending the request
     */
    async reportsStoreRequestOpts(requestParameters: ReportsStoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['reportableType'] == null) {
            throw new runtime.RequiredError(
                'reportableType',
                'Required parameter "reportableType" was null or undefined when calling reportsStore().'
            );
        }

        if (requestParameters['reportableId'] == null) {
            throw new runtime.RequiredError(
                'reportableId',
                'Required parameter "reportableId" was null or undefined when calling reportsStore().'
            );
        }

        if (requestParameters['reason'] == null) {
            throw new runtime.RequiredError(
                'reason',
                'Required parameter "reason" was null or undefined when calling reportsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['reportableType'] != null) {
            formParams.append('reportable_type', requestParameters['reportableType'] as any);
        }

        if (requestParameters['reportableId'] != null) {
            formParams.append('reportable_id', requestParameters['reportableId'] as any);
        }

        if (requestParameters['reason'] != null) {
            formParams.append('reason', requestParameters['reason'] as any);
        }

        if (requestParameters['description'] != null) {
            formParams.append('description', requestParameters['description'] as any);
        }

        if (requestParameters['evidenceImages'] != null) {
            requestParameters['evidenceImages'].forEach((element) => {
                formParams.append('evidence_images', element as any);
            })
        }


        let urlPath = `/reports`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     */
    async reportsStoreRaw(requestParameters: ReportsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReportsStore200Response>> {
        const requestOptions = await this.reportsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReportsStore200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async reportsStore(requestParameters: ReportsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReportsStore200Response> {
        const response = await this.reportsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ReportsStoreReportableTypeEnum = {
    User: 'User',
    Listing: 'Listing'
} as const;
export type ReportsStoreReportableTypeEnum = typeof ReportsStoreReportableTypeEnum[keyof typeof ReportsStoreReportableTypeEnum];
/**
 * @export
 */
export const ReportsStoreReasonEnum = {
    FakeListing: 'fake_listing',
    ScamDetected: 'scam_detected',
    OffensiveContent: 'offensive_content',
    WrongCategory: 'wrong_category',
    UnavailableProperty: 'unavailable_property',
    Impersonation: 'impersonation',
    Harassment: 'harassment'
} as const;
export type ReportsStoreReasonEnum = typeof ReportsStoreReasonEnum[keyof typeof ReportsStoreReasonEnum];
