/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  ListingsReviewsDestroy200Response,
  ListingsReviewsIndex200Response,
  ListingsReviewsStore201Response,
  ListingsReviewsStoreRequest,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    ListingsReviewsDestroy200ResponseFromJSON,
    ListingsReviewsDestroy200ResponseToJSON,
    ListingsReviewsIndex200ResponseFromJSON,
    ListingsReviewsIndex200ResponseToJSON,
    ListingsReviewsStore201ResponseFromJSON,
    ListingsReviewsStore201ResponseToJSON,
    ListingsReviewsStoreRequestFromJSON,
    ListingsReviewsStoreRequestToJSON,
} from '../models/index';

export interface ListingsReviewsDestroyRequest {
    listing: number;
    review: number;
}

export interface ListingsReviewsIndexRequest {
    listing: number;
}

export interface ListingsReviewsStoreOperationRequest {
    listing: number;
    listingsReviewsStoreRequest: ListingsReviewsStoreRequest;
}

/**
 * 
 */
export class ReviewsApi extends runtime.BaseAPI {

    /**
     * Creates request options for listingsReviewsDestroy without sending the request
     */
    async listingsReviewsDestroyRequestOpts(requestParameters: ListingsReviewsDestroyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsReviewsDestroy().'
            );
        }

        if (requestParameters['review'] == null) {
            throw new runtime.RequiredError(
                'review',
                'Required parameter "review" was null or undefined when calling listingsReviewsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/listings/{listing}/reviews/{review}`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));
        urlPath = urlPath.replace(`{${"review"}}`, encodeURIComponent(String(requestParameters['review'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a review. Only the author of the review can delete it.
     * Delete a review
     */
    async listingsReviewsDestroyRaw(requestParameters: ListingsReviewsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsReviewsDestroy200Response>> {
        const requestOptions = await this.listingsReviewsDestroyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsReviewsDestroy200ResponseFromJSON(jsonValue));
    }

    /**
     * Delete a review. Only the author of the review can delete it.
     * Delete a review
     */
    async listingsReviewsDestroy(requestParameters: ListingsReviewsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsReviewsDestroy200Response> {
        const response = await this.listingsReviewsDestroyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsReviewsIndex without sending the request
     */
    async listingsReviewsIndexRequestOpts(requestParameters: ListingsReviewsIndexRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsReviewsIndex().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/listings/{listing}/reviews`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns array of reviews without pagination
     * Get all reviews for a listing
     */
    async listingsReviewsIndexRaw(requestParameters: ListingsReviewsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsReviewsIndex200Response>> {
        const requestOptions = await this.listingsReviewsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsReviewsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns array of reviews without pagination
     * Get all reviews for a listing
     */
    async listingsReviewsIndex(requestParameters: ListingsReviewsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsReviewsIndex200Response> {
        const response = await this.listingsReviewsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listingsReviewsStore without sending the request
     */
    async listingsReviewsStoreRequestOpts(requestParameters: ListingsReviewsStoreOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['listing'] == null) {
            throw new runtime.RequiredError(
                'listing',
                'Required parameter "listing" was null or undefined when calling listingsReviewsStore().'
            );
        }

        if (requestParameters['listingsReviewsStoreRequest'] == null) {
            throw new runtime.RequiredError(
                'listingsReviewsStoreRequest',
                'Required parameter "listingsReviewsStoreRequest" was null or undefined when calling listingsReviewsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/listings/{listing}/reviews`;
        urlPath = urlPath.replace(`{${"listing"}}`, encodeURIComponent(String(requestParameters['listing'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ListingsReviewsStoreRequestToJSON(requestParameters['listingsReviewsStoreRequest']),
        };
    }

    /**
     * Member submits a review after making a call with the listing owner. A dialog should appear after the call ends.
     * Submit review after calling the host
     */
    async listingsReviewsStoreRaw(requestParameters: ListingsReviewsStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListingsReviewsStore201Response>> {
        const requestOptions = await this.listingsReviewsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListingsReviewsStore201ResponseFromJSON(jsonValue));
    }

    /**
     * Member submits a review after making a call with the listing owner. A dialog should appear after the call ends.
     * Submit review after calling the host
     */
    async listingsReviewsStore(requestParameters: ListingsReviewsStoreOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListingsReviewsStore201Response> {
        const response = await this.listingsReviewsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
