/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  SubscriptionsChargilyWebhookRequest,
  SubscriptionsCheckout200Response,
  SubscriptionsCheckoutRequest,
  SubscriptionsCurrent200Response,
  SubscriptionsIndex200Response,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    SubscriptionsChargilyWebhookRequestFromJSON,
    SubscriptionsChargilyWebhookRequestToJSON,
    SubscriptionsCheckout200ResponseFromJSON,
    SubscriptionsCheckout200ResponseToJSON,
    SubscriptionsCheckoutRequestFromJSON,
    SubscriptionsCheckoutRequestToJSON,
    SubscriptionsCurrent200ResponseFromJSON,
    SubscriptionsCurrent200ResponseToJSON,
    SubscriptionsIndex200ResponseFromJSON,
    SubscriptionsIndex200ResponseToJSON,
} from '../models/index';

export interface SubscriptionsChargilyWebhookOperationRequest {
    subscriptionsChargilyWebhookRequest: SubscriptionsChargilyWebhookRequest;
}

export interface SubscriptionsCheckoutOperationRequest {
    subscriptionsCheckoutRequest: SubscriptionsCheckoutRequest;
}

/**
 * 
 */
export class SubscriptionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for subscriptionsChargilyWebhook without sending the request
     */
    async subscriptionsChargilyWebhookRequestOpts(requestParameters: SubscriptionsChargilyWebhookOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['subscriptionsChargilyWebhookRequest'] == null) {
            throw new runtime.RequiredError(
                'subscriptionsChargilyWebhookRequest',
                'Required parameter "subscriptionsChargilyWebhookRequest" was null or undefined when calling subscriptionsChargilyWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/subscriptions/webhook/chargily`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscriptionsChargilyWebhookRequestToJSON(requestParameters['subscriptionsChargilyWebhookRequest']),
        };
    }

    /**
     * Webhook endpoint for Chargily payment notifications
     * Handle Chargily Webhook
     */
    async subscriptionsChargilyWebhookRaw(requestParameters: SubscriptionsChargilyWebhookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.subscriptionsChargilyWebhookRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Webhook endpoint for Chargily payment notifications
     * Handle Chargily Webhook
     */
    async subscriptionsChargilyWebhook(requestParameters: SubscriptionsChargilyWebhookOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.subscriptionsChargilyWebhookRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for subscriptionsCheckout without sending the request
     */
    async subscriptionsCheckoutRequestOpts(requestParameters: SubscriptionsCheckoutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['subscriptionsCheckoutRequest'] == null) {
            throw new runtime.RequiredError(
                'subscriptionsCheckoutRequest',
                'Required parameter "subscriptionsCheckoutRequest" was null or undefined when calling subscriptionsCheckout().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/subscriptions/checkout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscriptionsCheckoutRequestToJSON(requestParameters['subscriptionsCheckoutRequest']),
        };
    }

    /**
     * Create checkout session for subscription
     */
    async subscriptionsCheckoutRaw(requestParameters: SubscriptionsCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionsCheckout200Response>> {
        const requestOptions = await this.subscriptionsCheckoutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionsCheckout200ResponseFromJSON(jsonValue));
    }

    /**
     * Create checkout session for subscription
     */
    async subscriptionsCheckout(requestParameters: SubscriptionsCheckoutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionsCheckout200Response> {
        const response = await this.subscriptionsCheckoutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for subscriptionsCurrent without sending the request
     */
    async subscriptionsCurrentRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/subscriptions/current`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current user\'s active subscription
     */
    async subscriptionsCurrentRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionsCurrent200Response>> {
        const requestOptions = await this.subscriptionsCurrentRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionsCurrent200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current user\'s active subscription
     */
    async subscriptionsCurrent(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionsCurrent200Response> {
        const response = await this.subscriptionsCurrentRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for subscriptionsIndex without sending the request
     */
    async subscriptionsIndexRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/subscriptions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns list of subscription plans with features like monthly coins, active listings limit, etc.
     * Get all available subscription plans
     */
    async subscriptionsIndexRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionsIndex200Response>> {
        const requestOptions = await this.subscriptionsIndexRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns list of subscription plans with features like monthly coins, active listings limit, etc.
     * Get all available subscription plans
     */
    async subscriptionsIndex(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionsIndex200Response> {
        const response = await this.subscriptionsIndexRaw(initOverrides);
        return await response.value();
    }

}
