/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  WalletAddCoins200Response,
  WalletAddCoinsRequest,
  WalletShow200Response,
  WalletTransactions200Response,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    WalletAddCoins200ResponseFromJSON,
    WalletAddCoins200ResponseToJSON,
    WalletAddCoinsRequestFromJSON,
    WalletAddCoinsRequestToJSON,
    WalletShow200ResponseFromJSON,
    WalletShow200ResponseToJSON,
    WalletTransactions200ResponseFromJSON,
    WalletTransactions200ResponseToJSON,
} from '../models/index';

export interface WalletAddCoinsOperationRequest {
    walletAddCoinsRequest: WalletAddCoinsRequest;
}

export interface WalletTransactionsRequest {
    type?: string;
}

/**
 * 
 */
export class WalletApi extends runtime.BaseAPI {

    /**
     * Creates request options for walletAddCoins without sending the request
     */
    async walletAddCoinsRequestOpts(requestParameters: WalletAddCoinsOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['walletAddCoinsRequest'] == null) {
            throw new runtime.RequiredError(
                'walletAddCoinsRequest',
                'Required parameter "walletAddCoinsRequest" was null or undefined when calling walletAddCoins().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wallet/coins`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WalletAddCoinsRequestToJSON(requestParameters['walletAddCoinsRequest']),
        };
    }

    /**
     * Add coins to wallet (Buy coins package)
     */
    async walletAddCoinsRaw(requestParameters: WalletAddCoinsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletAddCoins200Response>> {
        const requestOptions = await this.walletAddCoinsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletAddCoins200ResponseFromJSON(jsonValue));
    }

    /**
     * Add coins to wallet (Buy coins package)
     */
    async walletAddCoins(requestParameters: WalletAddCoinsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletAddCoins200Response> {
        const response = await this.walletAddCoinsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for walletShow without sending the request
     */
    async walletShowRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wallet`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get user wallet balance
     */
    async walletShowRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletShow200Response>> {
        const requestOptions = await this.walletShowRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletShow200ResponseFromJSON(jsonValue));
    }

    /**
     * Get user wallet balance
     */
    async walletShow(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletShow200Response> {
        const response = await this.walletShowRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for walletTransactions without sending the request
     */
    async walletTransactionsRequestOpts(requestParameters: WalletTransactionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wallet/transactions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all transactions without pagination
     * Get wallet transaction history
     */
    async walletTransactionsRaw(requestParameters: WalletTransactionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletTransactions200Response>> {
        const requestOptions = await this.walletTransactionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WalletTransactions200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns all transactions without pagination
     * Get wallet transaction history
     */
    async walletTransactions(requestParameters: WalletTransactionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletTransactions200Response> {
        const response = await this.walletTransactionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
