/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AdResource
 */
export interface AdResource {
    /**
     * 
     * @type {number}
     * @memberof AdResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AdResource
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof AdResource
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdResource
     */
    imagePath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdResource
     */
    targetUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AdResource
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof AdResource
     */
    endDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof AdResource
     */
    status: boolean;
    /**
     * 
     * @type {string}
     * @memberof AdResource
     */
    referenceType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof AdResource
     */
    referenceId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof AdResource
     */
    memberId?: number | null;
}

/**
 * Check if a given object implements the AdResource interface.
 */
export function instanceOfAdResource(value: object): value is AdResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AdResourceFromJSON(json: any): AdResource {
    return AdResourceFromJSONTyped(json, false);
}

export function AdResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'imagePath': json['image_path'] == null ? undefined : json['image_path'],
        'targetUrl': json['target_url'] == null ? undefined : json['target_url'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'status': json['status'],
        'referenceType': json['reference_type'] == null ? undefined : json['reference_type'],
        'referenceId': json['reference_id'] == null ? undefined : json['reference_id'],
        'memberId': json['member_id'] == null ? undefined : json['member_id'],
    };
}

export function AdResourceToJSON(json: any): AdResource {
    return AdResourceToJSONTyped(json, false);
}

export function AdResourceToJSONTyped(value?: AdResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'image_path': value['imagePath'],
        'target_url': value['targetUrl'],
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'status': value['status'],
        'reference_type': value['referenceType'],
        'reference_id': value['referenceId'],
        'member_id': value['memberId'],
    };
}

