/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdsIndex200ResponseData } from './AdsIndex200ResponseData';
import {
    AdsIndex200ResponseDataFromJSON,
    AdsIndex200ResponseDataFromJSONTyped,
    AdsIndex200ResponseDataToJSON,
    AdsIndex200ResponseDataToJSONTyped,
} from './AdsIndex200ResponseData';

/**
 * 
 * @export
 * @interface AdsIndex200Response
 */
export interface AdsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AdsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {AdsIndex200ResponseData}
     * @memberof AdsIndex200Response
     */
    data: AdsIndex200ResponseData;
}

/**
 * Check if a given object implements the AdsIndex200Response interface.
 */
export function instanceOfAdsIndex200Response(value: object): value is AdsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AdsIndex200ResponseFromJSON(json: any): AdsIndex200Response {
    return AdsIndex200ResponseFromJSONTyped(json, false);
}

export function AdsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': AdsIndex200ResponseDataFromJSON(json['data']),
    };
}

export function AdsIndex200ResponseToJSON(json: any): AdsIndex200Response {
    return AdsIndex200ResponseToJSONTyped(json, false);
}

export function AdsIndex200ResponseToJSONTyped(value?: AdsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': AdsIndex200ResponseDataToJSON(value['data']),
    };
}

