/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { AdResource } from './AdResource';
import {
    AdResourceFromJSON,
    AdResourceFromJSONTyped,
    AdResourceToJSON,
    AdResourceToJSONTyped,
} from './AdResource';

/**
 * 
 * @export
 * @interface AdsIndex200ResponseData
 */
export interface AdsIndex200ResponseData {
    /**
     * 
     * @type {Array<AdResource>}
     * @memberof AdsIndex200ResponseData
     */
    ads: Array<AdResource>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof AdsIndex200ResponseData
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the AdsIndex200ResponseData interface.
 */
export function instanceOfAdsIndex200ResponseData(value: object): value is AdsIndex200ResponseData {
    if (!('ads' in value) || value['ads'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function AdsIndex200ResponseDataFromJSON(json: any): AdsIndex200ResponseData {
    return AdsIndex200ResponseDataFromJSONTyped(json, false);
}

export function AdsIndex200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdsIndex200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'ads': ((json['ads'] as Array<any>).map(AdResourceFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function AdsIndex200ResponseDataToJSON(json: any): AdsIndex200ResponseData {
    return AdsIndex200ResponseDataToJSONTyped(json, false);
}

export function AdsIndex200ResponseDataToJSONTyped(value?: AdsIndex200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ads': ((value['ads'] as Array<any>).map(AdResourceToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

