/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AdResource } from './AdResource';
import {
    AdResourceFromJSON,
    AdResourceFromJSONTyped,
    AdResourceToJSON,
    AdResourceToJSONTyped,
} from './AdResource';

/**
 * 
 * @export
 * @interface AdsShow200Response
 */
export interface AdsShow200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AdsShow200Response
     */
    success: boolean;
    /**
     * 
     * @type {AdResource}
     * @memberof AdsShow200Response
     */
    data: AdResource;
}

/**
 * Check if a given object implements the AdsShow200Response interface.
 */
export function instanceOfAdsShow200Response(value: object): value is AdsShow200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AdsShow200ResponseFromJSON(json: any): AdsShow200Response {
    return AdsShow200ResponseFromJSONTyped(json, false);
}

export function AdsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': AdResourceFromJSON(json['data']),
    };
}

export function AdsShow200ResponseToJSON(json: any): AdsShow200Response {
    return AdsShow200ResponseToJSONTyped(json, false);
}

export function AdsShow200ResponseToJSONTyped(value?: AdsShow200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': AdResourceToJSON(value['data']),
    };
}

