/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiChatRequestHistoryInner } from './AiChatRequestHistoryInner';
import {
    AiChatRequestHistoryInnerFromJSON,
    AiChatRequestHistoryInnerFromJSONTyped,
    AiChatRequestHistoryInnerToJSON,
    AiChatRequestHistoryInnerToJSONTyped,
} from './AiChatRequestHistoryInner';

/**
 * 
 * @export
 * @interface AiChatRequest
 */
export interface AiChatRequest {
    /**
     * User's message to the AI.
     * @type {string}
     * @memberof AiChatRequest
     */
    message: string;
    /**
     * Optional conversation history for context-aware dialogue.
     * @type {Array<AiChatRequestHistoryInner>}
     * @memberof AiChatRequest
     */
    history?: Array<AiChatRequestHistoryInner>;
}

/**
 * Check if a given object implements the AiChatRequest interface.
 */
export function instanceOfAiChatRequest(value: object): value is AiChatRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AiChatRequestFromJSON(json: any): AiChatRequest {
    return AiChatRequestFromJSONTyped(json, false);
}

export function AiChatRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'history': json['history'] == null ? undefined : ((json['history'] as Array<any>).map(AiChatRequestHistoryInnerFromJSON)),
    };
}

export function AiChatRequestToJSON(json: any): AiChatRequest {
    return AiChatRequestToJSONTyped(json, false);
}

export function AiChatRequestToJSONTyped(value?: AiChatRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'history': value['history'] == null ? undefined : ((value['history'] as Array<any>).map(AiChatRequestHistoryInnerToJSON)),
    };
}

