/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AiChatRequestHistoryInner
 */
export interface AiChatRequestHistoryInner {
    /**
     * 
     * @type {AiChatRequestHistoryInnerRoleEnum}
     * @memberof AiChatRequestHistoryInner
     */
    role?: AiChatRequestHistoryInnerRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof AiChatRequestHistoryInner
     */
    content?: string;
}


/**
 * @export
 */
export const AiChatRequestHistoryInnerRoleEnum = {
    User: 'user',
    Assistant: 'assistant'
} as const;
export type AiChatRequestHistoryInnerRoleEnum = typeof AiChatRequestHistoryInnerRoleEnum[keyof typeof AiChatRequestHistoryInnerRoleEnum];


/**
 * Check if a given object implements the AiChatRequestHistoryInner interface.
 */
export function instanceOfAiChatRequestHistoryInner(value: object): value is AiChatRequestHistoryInner {
    return true;
}

export function AiChatRequestHistoryInnerFromJSON(json: any): AiChatRequestHistoryInner {
    return AiChatRequestHistoryInnerFromJSONTyped(json, false);
}

export function AiChatRequestHistoryInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChatRequestHistoryInner {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : json['role'],
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function AiChatRequestHistoryInnerToJSON(json: any): AiChatRequestHistoryInner {
    return AiChatRequestHistoryInnerToJSONTyped(json, false);
}

export function AiChatRequestHistoryInnerToJSONTyped(value?: AiChatRequestHistoryInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role': value['role'],
        'content': value['content'],
    };
}

