/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingResource } from './ListingResource';
import {
    ListingResourceFromJSON,
    ListingResourceFromJSONTyped,
    ListingResourceToJSON,
    ListingResourceToJSONTyped,
} from './ListingResource';

/**
 * 
 * @export
 * @interface AiChat200ResponseData
 */
export interface AiChat200ResponseData {
    /**
     * AI's textual response.
     * @type {string}
     * @memberof AiChat200ResponseData
     */
    reply?: string;
    /**
     * List of recommended properties based on the chat.
     * @type {Array<ListingResource>}
     * @memberof AiChat200ResponseData
     */
    recommendations?: Array<ListingResource>;
}

/**
 * Check if a given object implements the AiChat200ResponseData interface.
 */
export function instanceOfAiChat200ResponseData(value: object): value is AiChat200ResponseData {
    return true;
}

export function AiChat200ResponseDataFromJSON(json: any): AiChat200ResponseData {
    return AiChat200ResponseDataFromJSONTyped(json, false);
}

export function AiChat200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChat200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'reply': json['reply'] == null ? undefined : json['reply'],
        'recommendations': json['recommendations'] == null ? undefined : ((json['recommendations'] as Array<any>).map(ListingResourceFromJSON)),
    };
}

export function AiChat200ResponseDataToJSON(json: any): AiChat200ResponseData {
    return AiChat200ResponseDataToJSONTyped(json, false);
}

export function AiChat200ResponseDataToJSONTyped(value?: AiChat200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reply': value['reply'],
        'recommendations': value['recommendations'] == null ? undefined : ((value['recommendations'] as Array<any>).map(ListingResourceToJSON)),
    };
}

