/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AiChat200ResponseData } from './AiChat200ResponseData';
import {
    AiChat200ResponseDataFromJSON,
    AiChat200ResponseDataFromJSONTyped,
    AiChat200ResponseDataToJSON,
    AiChat200ResponseDataToJSONTyped,
} from './AiChat200ResponseData';

/**
 * 
 * @export
 * @interface AiChat200Response
 */
export interface AiChat200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AiChat200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AiChat200Response
     */
    message?: string;
    /**
     * 
     * @type {AiChat200ResponseData}
     * @memberof AiChat200Response
     */
    data?: AiChat200ResponseData;
}

/**
 * Check if a given object implements the AiChat200Response interface.
 */
export function instanceOfAiChat200Response(value: object): value is AiChat200Response {
    return true;
}

export function AiChat200ResponseFromJSON(json: any): AiChat200Response {
    return AiChat200ResponseFromJSONTyped(json, false);
}

export function AiChat200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AiChat200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : AiChat200ResponseDataFromJSON(json['data']),
    };
}

export function AiChat200ResponseToJSON(json: any): AiChat200Response {
    return AiChat200ResponseToJSONTyped(json, false);
}

export function AiChat200ResponseToJSONTyped(value?: AiChat200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': AiChat200ResponseDataToJSON(value['data']),
    };
}

