/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppInfoIndex200ResponseData } from './AppInfoIndex200ResponseData';
import {
    AppInfoIndex200ResponseDataFromJSON,
    AppInfoIndex200ResponseDataFromJSONTyped,
    AppInfoIndex200ResponseDataToJSON,
    AppInfoIndex200ResponseDataToJSONTyped,
} from './AppInfoIndex200ResponseData';

/**
 * 
 * @export
 * @interface AppInfoIndex200Response
 */
export interface AppInfoIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AppInfoIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {AppInfoIndex200ResponseData}
     * @memberof AppInfoIndex200Response
     */
    data: AppInfoIndex200ResponseData;
}

/**
 * Check if a given object implements the AppInfoIndex200Response interface.
 */
export function instanceOfAppInfoIndex200Response(value: object): value is AppInfoIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AppInfoIndex200ResponseFromJSON(json: any): AppInfoIndex200Response {
    return AppInfoIndex200ResponseFromJSONTyped(json, false);
}

export function AppInfoIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': AppInfoIndex200ResponseDataFromJSON(json['data']),
    };
}

export function AppInfoIndex200ResponseToJSON(json: any): AppInfoIndex200Response {
    return AppInfoIndex200ResponseToJSONTyped(json, false);
}

export function AppInfoIndex200ResponseToJSONTyped(value?: AppInfoIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': AppInfoIndex200ResponseDataToJSON(value['data']),
    };
}

