/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppInfoResource
 */
export interface AppInfoResource {
    /**
     * 
     * @type {number}
     * @memberof AppInfoResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResource
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResource
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResource
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof AppInfoResource
     */
    language?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AppInfoResource
     */
    updatedAt?: Date | null;
}

/**
 * Check if a given object implements the AppInfoResource interface.
 */
export function instanceOfAppInfoResource(value: object): value is AppInfoResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function AppInfoResourceFromJSON(json: any): AppInfoResource {
    return AppInfoResourceFromJSONTyped(json, false);
}

export function AppInfoResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'key': json['key'],
        'value': json['value'],
        'language': json['language'] == null ? undefined : json['language'],
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function AppInfoResourceToJSON(json: any): AppInfoResource {
    return AppInfoResourceToJSONTyped(json, false);
}

export function AppInfoResourceToJSONTyped(value?: AppInfoResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'key': value['key'],
        'value': value['value'],
        'language': value['language'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

