/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppInfoResource } from './AppInfoResource';
import {
    AppInfoResourceFromJSON,
    AppInfoResourceFromJSONTyped,
    AppInfoResourceToJSON,
    AppInfoResourceToJSONTyped,
} from './AppInfoResource';

/**
 * 
 * @export
 * @interface AppInfoIndex200ResponseData
 */
export interface AppInfoIndex200ResponseData {
    /**
     * 
     * @type {Array<AppInfoResource>}
     * @memberof AppInfoIndex200ResponseData
     */
    appInfo: Array<AppInfoResource>;
}

/**
 * Check if a given object implements the AppInfoIndex200ResponseData interface.
 */
export function instanceOfAppInfoIndex200ResponseData(value: object): value is AppInfoIndex200ResponseData {
    if (!('appInfo' in value) || value['appInfo'] === undefined) return false;
    return true;
}

export function AppInfoIndex200ResponseDataFromJSON(json: any): AppInfoIndex200ResponseData {
    return AppInfoIndex200ResponseDataFromJSONTyped(json, false);
}

export function AppInfoIndex200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoIndex200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'appInfo': ((json['app_info'] as Array<any>).map(AppInfoResourceFromJSON)),
    };
}

export function AppInfoIndex200ResponseDataToJSON(json: any): AppInfoIndex200ResponseData {
    return AppInfoIndex200ResponseDataToJSONTyped(json, false);
}

export function AppInfoIndex200ResponseDataToJSONTyped(value?: AppInfoIndex200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_info': ((value['appInfo'] as Array<any>).map(AppInfoResourceToJSON)),
    };
}

