/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface AuthLogout200Response
 */
export interface AuthLogout200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogout200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof AuthLogout200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthLogout200ResponseStatusEnum}
     * @memberof AuthLogout200Response
     */
    status: AuthLogout200ResponseStatusEnum;
}


/**
 * @export
 */
export const AuthLogout200ResponseStatusEnum = {
    NUMBER_200: 200
} as const;
export type AuthLogout200ResponseStatusEnum = typeof AuthLogout200ResponseStatusEnum[keyof typeof AuthLogout200ResponseStatusEnum];


/**
 * Check if a given object implements the AuthLogout200Response interface.
 */
export function instanceOfAuthLogout200Response(value: object): value is AuthLogout200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AuthLogout200ResponseFromJSON(json: any): AuthLogout200Response {
    return AuthLogout200ResponseFromJSONTyped(json, false);
}

export function AuthLogout200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogout200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'status': json['status'],
    };
}

export function AuthLogout200ResponseToJSON(json: any): AuthLogout200Response {
    return AuthLogout200ResponseToJSONTyped(json, false);
}

export function AuthLogout200ResponseToJSONTyped(value?: AuthLogout200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'status': value['status'],
    };
}

