/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';
import type { AuthLogin200ResponseData } from './AuthLogin200ResponseData';
import {
    AuthLogin200ResponseDataFromJSON,
    AuthLogin200ResponseDataFromJSONTyped,
    AuthLogin200ResponseDataToJSON,
    AuthLogin200ResponseDataToJSONTyped,
} from './AuthLogin200ResponseData';

/**
 * 
 * @export
 * @interface AuthLogin200Response
 */
export interface AuthLogin200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogin200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof AuthLogin200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthLogin200ResponseStatusEnum}
     * @memberof AuthLogin200Response
     */
    status: AuthLogin200ResponseStatusEnum;
    /**
     * 
     * @type {AuthLogin200ResponseData}
     * @memberof AuthLogin200Response
     */
    data: AuthLogin200ResponseData;
}


/**
 * @export
 */
export const AuthLogin200ResponseStatusEnum = {
    NUMBER_200: 200
} as const;
export type AuthLogin200ResponseStatusEnum = typeof AuthLogin200ResponseStatusEnum[keyof typeof AuthLogin200ResponseStatusEnum];


/**
 * Check if a given object implements the AuthLogin200Response interface.
 */
export function instanceOfAuthLogin200Response(value: object): value is AuthLogin200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AuthLogin200ResponseFromJSON(json: any): AuthLogin200Response {
    return AuthLogin200ResponseFromJSONTyped(json, false);
}

export function AuthLogin200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogin200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'status': json['status'],
        'data': AuthLogin200ResponseDataFromJSON(json['data']),
    };
}

export function AuthLogin200ResponseToJSON(json: any): AuthLogin200Response {
    return AuthLogin200ResponseToJSONTyped(json, false);
}

export function AuthLogin200ResponseToJSONTyped(value?: AuthLogin200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'status': value['status'],
        'data': AuthLogin200ResponseDataToJSON(value['data']),
    };
}

