/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberProfileResource } from './MemberProfileResource';
import {
    MemberProfileResourceFromJSON,
    MemberProfileResourceFromJSONTyped,
    MemberProfileResourceToJSON,
    MemberProfileResourceToJSONTyped,
} from './MemberProfileResource';

/**
 * 
 * @export
 * @interface AuthLogin200ResponseData
 */
export interface AuthLogin200ResponseData {
    /**
     * Create new token
     * @type {string}
     * @memberof AuthLogin200ResponseData
     */
    token: string;
    /**
     * 
     * @type {MemberProfileResource}
     * @memberof AuthLogin200ResponseData
     */
    user: MemberProfileResource;
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogin200ResponseData
     */
    fillName: boolean;
}

/**
 * Check if a given object implements the AuthLogin200ResponseData interface.
 */
export function instanceOfAuthLogin200ResponseData(value: object): value is AuthLogin200ResponseData {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('fillName' in value) || value['fillName'] === undefined) return false;
    return true;
}

export function AuthLogin200ResponseDataFromJSON(json: any): AuthLogin200ResponseData {
    return AuthLogin200ResponseDataFromJSONTyped(json, false);
}

export function AuthLogin200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogin200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'user': MemberProfileResourceFromJSON(json['user']),
        'fillName': json['fill_name'],
    };
}

export function AuthLogin200ResponseDataToJSON(json: any): AuthLogin200ResponseData {
    return AuthLogin200ResponseDataToJSONTyped(json, false);
}

export function AuthLogin200ResponseDataToJSONTyped(value?: AuthLogin200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'user': MemberProfileResourceToJSON(value['user']),
        'fill_name': value['fillName'],
    };
}

