/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface AuthLogin401Response
 */
export interface AuthLogin401Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogin401Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof AuthLogin401Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthLogin401ResponseStatusEnum}
     * @memberof AuthLogin401Response
     */
    status: AuthLogin401ResponseStatusEnum;
}


/**
 * @export
 */
export const AuthLogin401ResponseStatusEnum = {
    NUMBER_401: 401
} as const;
export type AuthLogin401ResponseStatusEnum = typeof AuthLogin401ResponseStatusEnum[keyof typeof AuthLogin401ResponseStatusEnum];


/**
 * Check if a given object implements the AuthLogin401Response interface.
 */
export function instanceOfAuthLogin401Response(value: object): value is AuthLogin401Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AuthLogin401ResponseFromJSON(json: any): AuthLogin401Response {
    return AuthLogin401ResponseFromJSONTyped(json, false);
}

export function AuthLogin401ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogin401Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'status': json['status'],
    };
}

export function AuthLogin401ResponseToJSON(json: any): AuthLogin401Response {
    return AuthLogin401ResponseToJSONTyped(json, false);
}

export function AuthLogin401ResponseToJSONTyped(value?: AuthLogin401Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'status': value['status'],
    };
}

