/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface AuthLogin403Response
 */
export interface AuthLogin403Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthLogin403Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof AuthLogin403Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthLogin403ResponseStatusEnum}
     * @memberof AuthLogin403Response
     */
    status: AuthLogin403ResponseStatusEnum;
}


/**
 * @export
 */
export const AuthLogin403ResponseStatusEnum = {
    NUMBER_403: 403
} as const;
export type AuthLogin403ResponseStatusEnum = typeof AuthLogin403ResponseStatusEnum[keyof typeof AuthLogin403ResponseStatusEnum];


/**
 * Check if a given object implements the AuthLogin403Response interface.
 */
export function instanceOfAuthLogin403Response(value: object): value is AuthLogin403Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AuthLogin403ResponseFromJSON(json: any): AuthLogin403Response {
    return AuthLogin403ResponseFromJSONTyped(json, false);
}

export function AuthLogin403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLogin403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'status': json['status'],
    };
}

export function AuthLogin403ResponseToJSON(json: any): AuthLogin403Response {
    return AuthLogin403ResponseToJSONTyped(json, false);
}

export function AuthLogin403ResponseToJSONTyped(value?: AuthLogin403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'status': value['status'],
    };
}

