/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginRequest
 */
export interface AuthLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginRequest
     */
    login: string;
    /**
     * Can be email or phone
     * @type {string}
     * @memberof AuthLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the AuthLoginRequest interface.
 */
export function instanceOfAuthLoginRequest(value: object): value is AuthLoginRequest {
    if (!('login' in value) || value['login'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthLoginRequestFromJSON(json: any): AuthLoginRequest {
    return AuthLoginRequestFromJSONTyped(json, false);
}

export function AuthLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
    };
}

export function AuthLoginRequestToJSON(json: any): AuthLoginRequest {
    return AuthLoginRequestToJSONTyped(json, false);
}

export function AuthLoginRequestToJSONTyped(value?: AuthLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'login': value['login'],
        'password': value['password'],
    };
}

