/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberResource } from './MemberResource';
import {
    MemberResourceFromJSON,
    MemberResourceFromJSONTyped,
    MemberResourceToJSON,
    MemberResourceToJSONTyped,
} from './MemberResource';

/**
 * 
 * @export
 * @interface CallReviewResource
 */
export interface CallReviewResource {
    /**
     * 
     * @type {number}
     * @memberof CallReviewResource
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof CallReviewResource
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof CallReviewResource
     */
    comment?: string | null;
    /**
     * 
     * @type {MemberResource}
     * @memberof CallReviewResource
     */
    reviewer: MemberResource;
    /**
     * 
     * @type {Date}
     * @memberof CallReviewResource
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CallReviewResource interface.
 */
export function instanceOfCallReviewResource(value: object): value is CallReviewResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('reviewer' in value) || value['reviewer'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CallReviewResourceFromJSON(json: any): CallReviewResource {
    return CallReviewResourceFromJSONTyped(json, false);
}

export function CallReviewResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallReviewResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'rating': json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'reviewer': MemberResourceFromJSON(json['reviewer']),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CallReviewResourceToJSON(json: any): CallReviewResource {
    return CallReviewResourceToJSONTyped(json, false);
}

export function CallReviewResourceToJSONTyped(value?: CallReviewResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'rating': value['rating'],
        'comment': value['comment'],
        'reviewer': MemberResourceToJSON(value['reviewer']),
        'created_at': value['createdAt'].toISOString(),
    };
}

