/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatSessionsStoreRequest
 */
export interface ChatSessionsStoreRequest {
    /**
     * Optional - Start chat about a specific listing
     * @type {number}
     * @memberof ChatSessionsStoreRequest
     */
    listingId?: number | null;
}

/**
 * Check if a given object implements the ChatSessionsStoreRequest interface.
 */
export function instanceOfChatSessionsStoreRequest(value: object): value is ChatSessionsStoreRequest {
    return true;
}

export function ChatSessionsStoreRequestFromJSON(json: any): ChatSessionsStoreRequest {
    return ChatSessionsStoreRequestFromJSONTyped(json, false);
}

export function ChatSessionsStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSessionsStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listing_id'] == null ? undefined : json['listing_id'],
    };
}

export function ChatSessionsStoreRequestToJSON(json: any): ChatSessionsStoreRequest {
    return ChatSessionsStoreRequestToJSONTyped(json, false);
}

export function ChatSessionsStoreRequestToJSONTyped(value?: ChatSessionsStoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listing_id': value['listingId'],
    };
}

