/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatSessionResource
 */
export interface ChatSessionResource {
    /**
     * 
     * @type {number}
     * @memberof ChatSessionResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ChatSessionResource
     */
    sessionToken: string;
    /**
     * 
     * @type {Date}
     * @memberof ChatSessionResource
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ChatSessionResource
     */
    endedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChatSessionResource
     */
    isActive: boolean;
    /**
     * 
     * @type {number}
     * @memberof ChatSessionResource
     */
    chatSessionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChatSessionResource
     */
    memberId: number;
}

/**
 * Check if a given object implements the ChatSessionResource interface.
 */
export function instanceOfChatSessionResource(value: object): value is ChatSessionResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('sessionToken' in value) || value['sessionToken'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    return true;
}

export function ChatSessionResourceFromJSON(json: any): ChatSessionResource {
    return ChatSessionResourceFromJSONTyped(json, false);
}

export function ChatSessionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSessionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'sessionToken': json['session_token'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'endedAt': json['ended_at'] == null ? undefined : (new Date(json['ended_at'])),
        'isActive': json['is_active'],
        'chatSessionId': json['chat_session_id'] == null ? undefined : json['chat_session_id'],
        'memberId': json['member_id'],
    };
}

export function ChatSessionResourceToJSON(json: any): ChatSessionResource {
    return ChatSessionResourceToJSONTyped(json, false);
}

export function ChatSessionResourceToJSONTyped(value?: ChatSessionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'session_token': value['sessionToken'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'ended_at': value['endedAt'] == null ? value['endedAt'] : value['endedAt'].toISOString(),
        'is_active': value['isActive'],
        'chat_session_id': value['chatSessionId'],
        'member_id': value['memberId'],
    };
}

