/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessageResource } from './ChatMessageResource';
import {
    ChatMessageResourceFromJSON,
    ChatMessageResourceFromJSONTyped,
    ChatMessageResourceToJSON,
    ChatMessageResourceToJSONTyped,
} from './ChatMessageResource';
import type { ChatMessagesStore201ResponseDataBotMessage } from './ChatMessagesStore201ResponseDataBotMessage';
import {
    ChatMessagesStore201ResponseDataBotMessageFromJSON,
    ChatMessagesStore201ResponseDataBotMessageFromJSONTyped,
    ChatMessagesStore201ResponseDataBotMessageToJSON,
    ChatMessagesStore201ResponseDataBotMessageToJSONTyped,
} from './ChatMessagesStore201ResponseDataBotMessage';

/**
 * 
 * @export
 * @interface ChatMessagesStore201ResponseData
 */
export interface ChatMessagesStore201ResponseData {
    /**
     * 
     * @type {ChatMessageResource}
     * @memberof ChatMessagesStore201ResponseData
     */
    userMessage?: ChatMessageResource;
    /**
     * 
     * @type {ChatMessagesStore201ResponseDataBotMessage}
     * @memberof ChatMessagesStore201ResponseData
     */
    botMessage?: ChatMessagesStore201ResponseDataBotMessage;
}

/**
 * Check if a given object implements the ChatMessagesStore201ResponseData interface.
 */
export function instanceOfChatMessagesStore201ResponseData(value: object): value is ChatMessagesStore201ResponseData {
    return true;
}

export function ChatMessagesStore201ResponseDataFromJSON(json: any): ChatMessagesStore201ResponseData {
    return ChatMessagesStore201ResponseDataFromJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessagesStore201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'userMessage': json['user_message'] == null ? undefined : ChatMessageResourceFromJSON(json['user_message']),
        'botMessage': json['bot_message'] == null ? undefined : ChatMessagesStore201ResponseDataBotMessageFromJSON(json['bot_message']),
    };
}

export function ChatMessagesStore201ResponseDataToJSON(json: any): ChatMessagesStore201ResponseData {
    return ChatMessagesStore201ResponseDataToJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseDataToJSONTyped(value?: ChatMessagesStore201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_message': ChatMessageResourceToJSON(value['userMessage']),
        'bot_message': ChatMessagesStore201ResponseDataBotMessageToJSON(value['botMessage']),
    };
}

