/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessagesStore201ResponseData } from './ChatMessagesStore201ResponseData';
import {
    ChatMessagesStore201ResponseDataFromJSON,
    ChatMessagesStore201ResponseDataFromJSONTyped,
    ChatMessagesStore201ResponseDataToJSON,
    ChatMessagesStore201ResponseDataToJSONTyped,
} from './ChatMessagesStore201ResponseData';

/**
 * 
 * @export
 * @interface ChatMessagesStore201Response
 */
export interface ChatMessagesStore201Response {
    /**
     * 
     * @type {boolean}
     * @memberof ChatMessagesStore201Response
     */
    success?: boolean;
    /**
     * 
     * @type {ChatMessagesStore201ResponseData}
     * @memberof ChatMessagesStore201Response
     */
    data?: ChatMessagesStore201ResponseData;
}

/**
 * Check if a given object implements the ChatMessagesStore201Response interface.
 */
export function instanceOfChatMessagesStore201Response(value: object): value is ChatMessagesStore201Response {
    return true;
}

export function ChatMessagesStore201ResponseFromJSON(json: any): ChatMessagesStore201Response {
    return ChatMessagesStore201ResponseFromJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessagesStore201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : ChatMessagesStore201ResponseDataFromJSON(json['data']),
    };
}

export function ChatMessagesStore201ResponseToJSON(json: any): ChatMessagesStore201Response {
    return ChatMessagesStore201ResponseToJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseToJSONTyped(value?: ChatMessagesStore201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ChatMessagesStore201ResponseDataToJSON(value['data']),
    };
}

