/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessageResource
 */
export interface ChatMessageResource {
    /**
     * 
     * @type {number}
     * @memberof ChatMessageResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessageResource
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChatMessageResource
     */
    isBot: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessageResource
     */
    createdAt: Date | null;
    /**
     * enum(user, bot) : void
     * @type {string}
     * @memberof ChatMessageResource
     */
    sender: string;
}

/**
 * Check if a given object implements the ChatMessageResource interface.
 */
export function instanceOfChatMessageResource(value: object): value is ChatMessageResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('isBot' in value) || value['isBot'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('sender' in value) || value['sender'] === undefined) return false;
    return true;
}

export function ChatMessageResourceFromJSON(json: any): ChatMessageResource {
    return ChatMessageResourceFromJSONTyped(json, false);
}

export function ChatMessageResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessageResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'message': json['message'],
        'isBot': json['is_bot'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'sender': json['sender'],
    };
}

export function ChatMessageResourceToJSON(json: any): ChatMessageResource {
    return ChatMessageResourceToJSONTyped(json, false);
}

export function ChatMessageResourceToJSONTyped(value?: ChatMessageResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
        'is_bot': value['isBot'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'sender': value['sender'],
    };
}

