/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessagesStore201ResponseDataBotMessageRecommendedInner
 */
export interface ChatMessagesStore201ResponseDataBotMessageRecommendedInner {
    /**
     * 
     * @type {number}
     * @memberof ChatMessagesStore201ResponseDataBotMessageRecommendedInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessagesStore201ResponseDataBotMessageRecommendedInner
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ChatMessagesStore201ResponseDataBotMessageRecommendedInner
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessagesStore201ResponseDataBotMessageRecommendedInner
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatMessagesStore201ResponseDataBotMessageRecommendedInner
     */
    location?: string;
    /**
     * 
     * @type {number}
     * @memberof ChatMessagesStore201ResponseDataBotMessageRecommendedInner
     */
    rating?: number;
}

/**
 * Check if a given object implements the ChatMessagesStore201ResponseDataBotMessageRecommendedInner interface.
 */
export function instanceOfChatMessagesStore201ResponseDataBotMessageRecommendedInner(value: object): value is ChatMessagesStore201ResponseDataBotMessageRecommendedInner {
    return true;
}

export function ChatMessagesStore201ResponseDataBotMessageRecommendedInnerFromJSON(json: any): ChatMessagesStore201ResponseDataBotMessageRecommendedInner {
    return ChatMessagesStore201ResponseDataBotMessageRecommendedInnerFromJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseDataBotMessageRecommendedInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessagesStore201ResponseDataBotMessageRecommendedInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'price': json['price'] == null ? undefined : json['price'],
        'image': json['image'] == null ? undefined : json['image'],
        'location': json['location'] == null ? undefined : json['location'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function ChatMessagesStore201ResponseDataBotMessageRecommendedInnerToJSON(json: any): ChatMessagesStore201ResponseDataBotMessageRecommendedInner {
    return ChatMessagesStore201ResponseDataBotMessageRecommendedInnerToJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseDataBotMessageRecommendedInnerToJSONTyped(value?: ChatMessagesStore201ResponseDataBotMessageRecommendedInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'price': value['price'],
        'image': value['image'],
        'location': value['location'],
        'rating': value['rating'],
    };
}

