/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatMessagesStore201ResponseDataBotMessageRecommendedInner } from './ChatMessagesStore201ResponseDataBotMessageRecommendedInner';
import {
    ChatMessagesStore201ResponseDataBotMessageRecommendedInnerFromJSON,
    ChatMessagesStore201ResponseDataBotMessageRecommendedInnerFromJSONTyped,
    ChatMessagesStore201ResponseDataBotMessageRecommendedInnerToJSON,
    ChatMessagesStore201ResponseDataBotMessageRecommendedInnerToJSONTyped,
} from './ChatMessagesStore201ResponseDataBotMessageRecommendedInner';

/**
 * 
 * @export
 * @interface ChatMessagesStore201ResponseDataBotMessage
 */
export interface ChatMessagesStore201ResponseDataBotMessage {
    /**
     * 
     * @type {number}
     * @memberof ChatMessagesStore201ResponseDataBotMessage
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatMessagesStore201ResponseDataBotMessage
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ChatMessagesStore201ResponseDataBotMessage
     */
    isBot?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ChatMessagesStore201ResponseDataBotMessage
     */
    createdAt?: Date;
    /**
     * List of recommended apartments by AI with clickable IDs
     * @type {Array<ChatMessagesStore201ResponseDataBotMessageRecommendedInner>}
     * @memberof ChatMessagesStore201ResponseDataBotMessage
     */
    recommended?: Array<ChatMessagesStore201ResponseDataBotMessageRecommendedInner> | null;
}

/**
 * Check if a given object implements the ChatMessagesStore201ResponseDataBotMessage interface.
 */
export function instanceOfChatMessagesStore201ResponseDataBotMessage(value: object): value is ChatMessagesStore201ResponseDataBotMessage {
    return true;
}

export function ChatMessagesStore201ResponseDataBotMessageFromJSON(json: any): ChatMessagesStore201ResponseDataBotMessage {
    return ChatMessagesStore201ResponseDataBotMessageFromJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseDataBotMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessagesStore201ResponseDataBotMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'message': json['message'] == null ? undefined : json['message'],
        'isBot': json['is_bot'] == null ? undefined : json['is_bot'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'recommended': json['recommended'] == null ? undefined : ((json['recommended'] as Array<any>).map(ChatMessagesStore201ResponseDataBotMessageRecommendedInnerFromJSON)),
    };
}

export function ChatMessagesStore201ResponseDataBotMessageToJSON(json: any): ChatMessagesStore201ResponseDataBotMessage {
    return ChatMessagesStore201ResponseDataBotMessageToJSONTyped(json, false);
}

export function ChatMessagesStore201ResponseDataBotMessageToJSONTyped(value?: ChatMessagesStore201ResponseDataBotMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'message': value['message'],
        'is_bot': value['isBot'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'recommended': value['recommended'] == null ? undefined : ((value['recommended'] as Array<any>).map(ChatMessagesStore201ResponseDataBotMessageRecommendedInnerToJSON)),
    };
}

