/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatSessionResource } from './ChatSessionResource';
import {
    ChatSessionResourceFromJSON,
    ChatSessionResourceFromJSONTyped,
    ChatSessionResourceToJSON,
    ChatSessionResourceToJSONTyped,
} from './ChatSessionResource';

/**
 * 
 * @export
 * @interface ChatSessionsStore201Response
 */
export interface ChatSessionsStore201Response {
    /**
     * 
     * @type {boolean}
     * @memberof ChatSessionsStore201Response
     */
    success: boolean;
    /**
     * 
     * @type {ChatSessionResource}
     * @memberof ChatSessionsStore201Response
     */
    data: ChatSessionResource;
}

/**
 * Check if a given object implements the ChatSessionsStore201Response interface.
 */
export function instanceOfChatSessionsStore201Response(value: object): value is ChatSessionsStore201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ChatSessionsStore201ResponseFromJSON(json: any): ChatSessionsStore201Response {
    return ChatSessionsStore201ResponseFromJSONTyped(json, false);
}

export function ChatSessionsStore201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSessionsStore201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ChatSessionResourceFromJSON(json['data']),
    };
}

export function ChatSessionsStore201ResponseToJSON(json: any): ChatSessionsStore201Response {
    return ChatSessionsStore201ResponseToJSONTyped(json, false);
}

export function ChatSessionsStore201ResponseToJSONTyped(value?: ChatSessionsStore201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ChatSessionResourceToJSON(value['data']),
    };
}

