/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatSessionResource } from './ChatSessionResource';
import {
    ChatSessionResourceFromJSON,
    ChatSessionResourceFromJSONTyped,
    ChatSessionResourceToJSON,
    ChatSessionResourceToJSONTyped,
} from './ChatSessionResource';

/**
 * 
 * @export
 * @interface ChatSessionsIndex200Response
 */
export interface ChatSessionsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ChatSessionsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<ChatSessionResource>}
     * @memberof ChatSessionsIndex200Response
     */
    data: Array<ChatSessionResource>;
}

/**
 * Check if a given object implements the ChatSessionsIndex200Response interface.
 */
export function instanceOfChatSessionsIndex200Response(value: object): value is ChatSessionsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ChatSessionsIndex200ResponseFromJSON(json: any): ChatSessionsIndex200Response {
    return ChatSessionsIndex200ResponseFromJSONTyped(json, false);
}

export function ChatSessionsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatSessionsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(ChatSessionResourceFromJSON)),
    };
}

export function ChatSessionsIndex200ResponseToJSON(json: any): ChatSessionsIndex200Response {
    return ChatSessionsIndex200ResponseToJSONTyped(json, false);
}

export function ChatSessionsIndex200ResponseToJSONTyped(value?: ChatSessionsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(ChatSessionResourceToJSON)),
    };
}

