/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatMessagesStoreRequest
 */
export interface ChatMessagesStoreRequest {
    /**
     * 
     * @type {string}
     * @memberof ChatMessagesStoreRequest
     */
    message: string;
}

/**
 * Check if a given object implements the ChatMessagesStoreRequest interface.
 */
export function instanceOfChatMessagesStoreRequest(value: object): value is ChatMessagesStoreRequest {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ChatMessagesStoreRequestFromJSON(json: any): ChatMessagesStoreRequest {
    return ChatMessagesStoreRequestFromJSONTyped(json, false);
}

export function ChatMessagesStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatMessagesStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ChatMessagesStoreRequestToJSON(json: any): ChatMessagesStoreRequest {
    return ChatMessagesStoreRequestToJSONTyped(json, false);
}

export function ChatMessagesStoreRequestToJSONTyped(value?: ChatMessagesStoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

