/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeaturedListingsIndex200ResponseData } from './FeaturedListingsIndex200ResponseData';
import {
    FeaturedListingsIndex200ResponseDataFromJSON,
    FeaturedListingsIndex200ResponseDataFromJSONTyped,
    FeaturedListingsIndex200ResponseDataToJSON,
    FeaturedListingsIndex200ResponseDataToJSONTyped,
} from './FeaturedListingsIndex200ResponseData';

/**
 * 
 * @export
 * @interface FeaturedListingsIndex200Response
 */
export interface FeaturedListingsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof FeaturedListingsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {FeaturedListingsIndex200ResponseData}
     * @memberof FeaturedListingsIndex200Response
     */
    data: FeaturedListingsIndex200ResponseData;
}

/**
 * Check if a given object implements the FeaturedListingsIndex200Response interface.
 */
export function instanceOfFeaturedListingsIndex200Response(value: object): value is FeaturedListingsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function FeaturedListingsIndex200ResponseFromJSON(json: any): FeaturedListingsIndex200Response {
    return FeaturedListingsIndex200ResponseFromJSONTyped(json, false);
}

export function FeaturedListingsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeaturedListingsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': FeaturedListingsIndex200ResponseDataFromJSON(json['data']),
    };
}

export function FeaturedListingsIndex200ResponseToJSON(json: any): FeaturedListingsIndex200Response {
    return FeaturedListingsIndex200ResponseToJSONTyped(json, false);
}

export function FeaturedListingsIndex200ResponseToJSONTyped(value?: FeaturedListingsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': FeaturedListingsIndex200ResponseDataToJSON(value['data']),
    };
}

