/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingResource } from './ListingResource';
import {
    ListingResourceFromJSON,
    ListingResourceFromJSONTyped,
    ListingResourceToJSON,
    ListingResourceToJSONTyped,
} from './ListingResource';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface FeaturedListingResource
 */
export interface FeaturedListingResource {
    /**
     * 
     * @type {ListingResource}
     * @memberof FeaturedListingResource
     */
    listing?: ListingResource;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof FeaturedListingResource
     */
    meta?: PaginationMeta;
}

/**
 * Check if a given object implements the FeaturedListingResource interface.
 */
export function instanceOfFeaturedListingResource(value: object): value is FeaturedListingResource {
    return true;
}

export function FeaturedListingResourceFromJSON(json: any): FeaturedListingResource {
    return FeaturedListingResourceFromJSONTyped(json, false);
}

export function FeaturedListingResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeaturedListingResource {
    if (json == null) {
        return json;
    }
    return {
        
        'listing': json['listing'] == null ? undefined : ListingResourceFromJSON(json['listing']),
        'meta': json['meta'] == null ? undefined : PaginationMetaFromJSON(json['meta']),
    };
}

export function FeaturedListingResourceToJSON(json: any): FeaturedListingResource {
    return FeaturedListingResourceToJSONTyped(json, false);
}

export function FeaturedListingResourceToJSONTyped(value?: FeaturedListingResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listing': ListingResourceToJSON(value['listing']),
        'meta': PaginationMetaToJSON(value['meta']),
    };
}

