/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { FeaturedListingResource } from './FeaturedListingResource';
import {
    FeaturedListingResourceFromJSON,
    FeaturedListingResourceFromJSONTyped,
    FeaturedListingResourceToJSON,
    FeaturedListingResourceToJSONTyped,
} from './FeaturedListingResource';

/**
 * 
 * @export
 * @interface FeaturedListingsIndex200ResponseData
 */
export interface FeaturedListingsIndex200ResponseData {
    /**
     * 
     * @type {Array<FeaturedListingResource>}
     * @memberof FeaturedListingsIndex200ResponseData
     */
    featuredListings: Array<FeaturedListingResource>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof FeaturedListingsIndex200ResponseData
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the FeaturedListingsIndex200ResponseData interface.
 */
export function instanceOfFeaturedListingsIndex200ResponseData(value: object): value is FeaturedListingsIndex200ResponseData {
    if (!('featuredListings' in value) || value['featuredListings'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function FeaturedListingsIndex200ResponseDataFromJSON(json: any): FeaturedListingsIndex200ResponseData {
    return FeaturedListingsIndex200ResponseDataFromJSONTyped(json, false);
}

export function FeaturedListingsIndex200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeaturedListingsIndex200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'featuredListings': ((json['featured_listings'] as Array<any>).map(FeaturedListingResourceFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function FeaturedListingsIndex200ResponseDataToJSON(json: any): FeaturedListingsIndex200ResponseData {
    return FeaturedListingsIndex200ResponseDataToJSONTyped(json, false);
}

export function FeaturedListingsIndex200ResponseDataToJSONTyped(value?: FeaturedListingsIndex200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'featured_listings': ((value['featuredListings'] as Array<any>).map(FeaturedListingResourceToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

