/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingsBoostRequest
 */
export interface ListingsBoostRequest {
    /**
     * 
     * @type {number}
     * @memberof ListingsBoostRequest
     */
    durationDays: number;
    /**
     * 
     * @type {ListingsBoostRequestPaymentMethodEnum}
     * @memberof ListingsBoostRequest
     */
    paymentMethod?: ListingsBoostRequestPaymentMethodEnum;
}


/**
 * @export
 */
export const ListingsBoostRequestPaymentMethodEnum = {
    Chargily: 'chargily',
    Wallet: 'wallet'
} as const;
export type ListingsBoostRequestPaymentMethodEnum = typeof ListingsBoostRequestPaymentMethodEnum[keyof typeof ListingsBoostRequestPaymentMethodEnum];


/**
 * Check if a given object implements the ListingsBoostRequest interface.
 */
export function instanceOfListingsBoostRequest(value: object): value is ListingsBoostRequest {
    if (!('durationDays' in value) || value['durationDays'] === undefined) return false;
    return true;
}

export function ListingsBoostRequestFromJSON(json: any): ListingsBoostRequest {
    return ListingsBoostRequestFromJSONTyped(json, false);
}

export function ListingsBoostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsBoostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'durationDays': json['duration_days'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
    };
}

export function ListingsBoostRequestToJSON(json: any): ListingsBoostRequest {
    return ListingsBoostRequestToJSONTyped(json, false);
}

export function ListingsBoostRequestToJSONTyped(value?: ListingsBoostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_days': value['durationDays'],
        'payment_method': value['paymentMethod'],
    };
}

