/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberResource } from './MemberResource';
import {
    MemberResourceFromJSON,
    MemberResourceFromJSONTyped,
    MemberResourceToJSON,
    MemberResourceToJSONTyped,
} from './MemberResource';

/**
 * 
 * @export
 * @interface ListingsReviewsStore201ResponseData
 */
export interface ListingsReviewsStore201ResponseData {
    /**
     * 
     * @type {MemberResource}
     * @memberof ListingsReviewsStore201ResponseData
     */
    user?: MemberResource;
    /**
     * 
     * @type {string}
     * @memberof ListingsReviewsStore201ResponseData
     */
    review?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListingsReviewsStore201ResponseData
     */
    rating?: number;
}

/**
 * Check if a given object implements the ListingsReviewsStore201ResponseData interface.
 */
export function instanceOfListingsReviewsStore201ResponseData(value: object): value is ListingsReviewsStore201ResponseData {
    return true;
}

export function ListingsReviewsStore201ResponseDataFromJSON(json: any): ListingsReviewsStore201ResponseData {
    return ListingsReviewsStore201ResponseDataFromJSONTyped(json, false);
}

export function ListingsReviewsStore201ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsReviewsStore201ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : MemberResourceFromJSON(json['user']),
        'review': json['review'] == null ? undefined : json['review'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function ListingsReviewsStore201ResponseDataToJSON(json: any): ListingsReviewsStore201ResponseData {
    return ListingsReviewsStore201ResponseDataToJSONTyped(json, false);
}

export function ListingsReviewsStore201ResponseDataToJSONTyped(value?: ListingsReviewsStore201ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': MemberResourceToJSON(value['user']),
        'review': value['review'],
        'rating': value['rating'],
    };
}

