/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingsReviewsDestroy200Response
 */
export interface ListingsReviewsDestroy200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListingsReviewsDestroy200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListingsReviewsDestroy200Response
     */
    message: string;
}

/**
 * Check if a given object implements the ListingsReviewsDestroy200Response interface.
 */
export function instanceOfListingsReviewsDestroy200Response(value: object): value is ListingsReviewsDestroy200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ListingsReviewsDestroy200ResponseFromJSON(json: any): ListingsReviewsDestroy200Response {
    return ListingsReviewsDestroy200ResponseFromJSONTyped(json, false);
}

export function ListingsReviewsDestroy200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsReviewsDestroy200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function ListingsReviewsDestroy200ResponseToJSON(json: any): ListingsReviewsDestroy200Response {
    return ListingsReviewsDestroy200ResponseToJSONTyped(json, false);
}

export function ListingsReviewsDestroy200ResponseToJSONTyped(value?: ListingsReviewsDestroy200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

