/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingsReviewsStore201ResponseData } from './ListingsReviewsStore201ResponseData';
import {
    ListingsReviewsStore201ResponseDataFromJSON,
    ListingsReviewsStore201ResponseDataFromJSONTyped,
    ListingsReviewsStore201ResponseDataToJSON,
    ListingsReviewsStore201ResponseDataToJSONTyped,
} from './ListingsReviewsStore201ResponseData';

/**
 * 
 * @export
 * @interface ListingsReviewsStore201Response
 */
export interface ListingsReviewsStore201Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListingsReviewsStore201Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListingsReviewsStore201Response
     */
    message: string;
    /**
     * 
     * @type {ListingsReviewsStore201ResponseData}
     * @memberof ListingsReviewsStore201Response
     */
    data: ListingsReviewsStore201ResponseData;
}

/**
 * Check if a given object implements the ListingsReviewsStore201Response interface.
 */
export function instanceOfListingsReviewsStore201Response(value: object): value is ListingsReviewsStore201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListingsReviewsStore201ResponseFromJSON(json: any): ListingsReviewsStore201Response {
    return ListingsReviewsStore201ResponseFromJSONTyped(json, false);
}

export function ListingsReviewsStore201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsReviewsStore201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'data': ListingsReviewsStore201ResponseDataFromJSON(json['data']),
    };
}

export function ListingsReviewsStore201ResponseToJSON(json: any): ListingsReviewsStore201Response {
    return ListingsReviewsStore201ResponseToJSONTyped(json, false);
}

export function ListingsReviewsStore201ResponseToJSONTyped(value?: ListingsReviewsStore201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': ListingsReviewsStore201ResponseDataToJSON(value['data']),
    };
}

