/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListingsReviewsStoreRequest
 */
export interface ListingsReviewsStoreRequest {
    /**
     * 
     * @type {number}
     * @memberof ListingsReviewsStoreRequest
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof ListingsReviewsStoreRequest
     */
    review?: string | null;
}

/**
 * Check if a given object implements the ListingsReviewsStoreRequest interface.
 */
export function instanceOfListingsReviewsStoreRequest(value: object): value is ListingsReviewsStoreRequest {
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function ListingsReviewsStoreRequestFromJSON(json: any): ListingsReviewsStoreRequest {
    return ListingsReviewsStoreRequestFromJSONTyped(json, false);
}

export function ListingsReviewsStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsReviewsStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'],
        'review': json['review'] == null ? undefined : json['review'],
    };
}

export function ListingsReviewsStoreRequestToJSON(json: any): ListingsReviewsStoreRequest {
    return ListingsReviewsStoreRequestToJSONTyped(json, false);
}

export function ListingsReviewsStoreRequestToJSONTyped(value?: ListingsReviewsStoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
        'review': value['review'],
    };
}

