/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingsReviewsIndex200ResponseDataInner } from './ListingsReviewsIndex200ResponseDataInner';
import {
    ListingsReviewsIndex200ResponseDataInnerFromJSON,
    ListingsReviewsIndex200ResponseDataInnerFromJSONTyped,
    ListingsReviewsIndex200ResponseDataInnerToJSON,
    ListingsReviewsIndex200ResponseDataInnerToJSONTyped,
} from './ListingsReviewsIndex200ResponseDataInner';

/**
 * 
 * @export
 * @interface ListingsReviewsIndex200Response
 */
export interface ListingsReviewsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListingsReviewsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<ListingsReviewsIndex200ResponseDataInner>}
     * @memberof ListingsReviewsIndex200Response
     */
    data: Array<ListingsReviewsIndex200ResponseDataInner>;
}

/**
 * Check if a given object implements the ListingsReviewsIndex200Response interface.
 */
export function instanceOfListingsReviewsIndex200Response(value: object): value is ListingsReviewsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ListingsReviewsIndex200ResponseFromJSON(json: any): ListingsReviewsIndex200Response {
    return ListingsReviewsIndex200ResponseFromJSONTyped(json, false);
}

export function ListingsReviewsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsReviewsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(ListingsReviewsIndex200ResponseDataInnerFromJSON)),
    };
}

export function ListingsReviewsIndex200ResponseToJSON(json: any): ListingsReviewsIndex200Response {
    return ListingsReviewsIndex200ResponseToJSONTyped(json, false);
}

export function ListingsReviewsIndex200ResponseToJSONTyped(value?: ListingsReviewsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(ListingsReviewsIndex200ResponseDataInnerToJSON)),
    };
}

