/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberResource } from './MemberResource';
import {
    MemberResourceFromJSON,
    MemberResourceFromJSONTyped,
    MemberResourceToJSON,
    MemberResourceToJSONTyped,
} from './MemberResource';

/**
 * 
 * @export
 * @interface ListingsReviewsIndex200ResponseDataInner
 */
export interface ListingsReviewsIndex200ResponseDataInner {
    /**
     * 
     * @type {MemberResource}
     * @memberof ListingsReviewsIndex200ResponseDataInner
     */
    user: MemberResource;
    /**
     * 
     * @type {string}
     * @memberof ListingsReviewsIndex200ResponseDataInner
     */
    review?: string;
    /**
     * 
     * @type {number}
     * @memberof ListingsReviewsIndex200ResponseDataInner
     */
    rating: number;
}

/**
 * Check if a given object implements the ListingsReviewsIndex200ResponseDataInner interface.
 */
export function instanceOfListingsReviewsIndex200ResponseDataInner(value: object): value is ListingsReviewsIndex200ResponseDataInner {
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function ListingsReviewsIndex200ResponseDataInnerFromJSON(json: any): ListingsReviewsIndex200ResponseDataInner {
    return ListingsReviewsIndex200ResponseDataInnerFromJSONTyped(json, false);
}

export function ListingsReviewsIndex200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingsReviewsIndex200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'user': MemberResourceFromJSON(json['user']),
        'review': json['review'] == null ? undefined : json['review'],
        'rating': json['rating'],
    };
}

export function ListingsReviewsIndex200ResponseDataInnerToJSON(json: any): ListingsReviewsIndex200ResponseDataInner {
    return ListingsReviewsIndex200ResponseDataInnerToJSONTyped(json, false);
}

export function ListingsReviewsIndex200ResponseDataInnerToJSONTyped(value?: ListingsReviewsIndex200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': MemberResourceToJSON(value['user']),
        'review': value['review'],
        'rating': value['rating'],
    };
}

