/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberProfileResourceWalletBalance
 */
export interface MemberProfileResourceWalletBalance {
}

/**
 * Check if a given object implements the MemberProfileResourceWalletBalance interface.
 */
export function instanceOfMemberProfileResourceWalletBalance(value: object): value is MemberProfileResourceWalletBalance {
    return true;
}

export function MemberProfileResourceWalletBalanceFromJSON(json: any): MemberProfileResourceWalletBalance {
    return MemberProfileResourceWalletBalanceFromJSONTyped(json, false);
}

export function MemberProfileResourceWalletBalanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberProfileResourceWalletBalance {
    return json;
}

export function MemberProfileResourceWalletBalanceToJSON(json: any): MemberProfileResourceWalletBalance {
    return MemberProfileResourceWalletBalanceToJSONTyped(json, false);
}

export function MemberProfileResourceWalletBalanceToJSONTyped(value?: MemberProfileResourceWalletBalance | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

