/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MembersShow200ResponseData } from './MembersShow200ResponseData';
import {
    MembersShow200ResponseDataFromJSON,
    MembersShow200ResponseDataFromJSONTyped,
    MembersShow200ResponseDataToJSON,
    MembersShow200ResponseDataToJSONTyped,
} from './MembersShow200ResponseData';

/**
 * 
 * @export
 * @interface MembersShow200Response
 */
export interface MembersShow200Response {
    /**
     * 
     * @type {boolean}
     * @memberof MembersShow200Response
     */
    success: boolean;
    /**
     * 
     * @type {MembersShow200ResponseData}
     * @memberof MembersShow200Response
     */
    data: MembersShow200ResponseData;
}

/**
 * Check if a given object implements the MembersShow200Response interface.
 */
export function instanceOfMembersShow200Response(value: object): value is MembersShow200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function MembersShow200ResponseFromJSON(json: any): MembersShow200Response {
    return MembersShow200ResponseFromJSONTyped(json, false);
}

export function MembersShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembersShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': MembersShow200ResponseDataFromJSON(json['data']),
    };
}

export function MembersShow200ResponseToJSON(json: any): MembersShow200Response {
    return MembersShow200ResponseToJSONTyped(json, false);
}

export function MembersShow200ResponseToJSONTyped(value?: MembersShow200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': MembersShow200ResponseDataToJSON(value['data']),
    };
}

