/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberProfileResourceVerification
 */
export interface MemberProfileResourceVerification {
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfileResourceVerification
     */
    isMemberVerified: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfileResourceVerification
     */
    isAgentVerified: boolean;
}

/**
 * Check if a given object implements the MemberProfileResourceVerification interface.
 */
export function instanceOfMemberProfileResourceVerification(value: object): value is MemberProfileResourceVerification {
    if (!('isMemberVerified' in value) || value['isMemberVerified'] === undefined) return false;
    if (!('isAgentVerified' in value) || value['isAgentVerified'] === undefined) return false;
    return true;
}

export function MemberProfileResourceVerificationFromJSON(json: any): MemberProfileResourceVerification {
    return MemberProfileResourceVerificationFromJSONTyped(json, false);
}

export function MemberProfileResourceVerificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberProfileResourceVerification {
    if (json == null) {
        return json;
    }
    return {
        
        'isMemberVerified': json['is_member_verified'],
        'isAgentVerified': json['is_agent_verified'],
    };
}

export function MemberProfileResourceVerificationToJSON(json: any): MemberProfileResourceVerification {
    return MemberProfileResourceVerificationToJSONTyped(json, false);
}

export function MemberProfileResourceVerificationToJSONTyped(value?: MemberProfileResourceVerification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_member_verified': value['isMemberVerified'],
        'is_agent_verified': value['isAgentVerified'],
    };
}

