/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberProfileResourceVerification } from './MemberProfileResourceVerification';
import {
    MemberProfileResourceVerificationFromJSON,
    MemberProfileResourceVerificationFromJSONTyped,
    MemberProfileResourceVerificationToJSON,
    MemberProfileResourceVerificationToJSONTyped,
} from './MemberProfileResourceVerification';
import type { MemberProfileResourceWalletBalance } from './MemberProfileResourceWalletBalance';
import {
    MemberProfileResourceWalletBalanceFromJSON,
    MemberProfileResourceWalletBalanceFromJSONTyped,
    MemberProfileResourceWalletBalanceToJSON,
    MemberProfileResourceWalletBalanceToJSONTyped,
} from './MemberProfileResourceWalletBalance';

/**
 * 
 * @export
 * @interface MemberProfileResource
 */
export interface MemberProfileResource {
    /**
     * 
     * @type {string}
     * @memberof MemberProfileResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MemberProfileResource
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MemberProfileResource
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof MemberProfileResource
     */
    phone: string;
    /**
     * 
     * @type {boolean}
     * @memberof MemberProfileResource
     */
    hasPassword: boolean;
    /**
     * 
     * @type {string}
     * @memberof MemberProfileResource
     */
    profileImage: string;
    /**
     * 
     * @type {MemberProfileResourceVerification}
     * @memberof MemberProfileResource
     */
    verification: MemberProfileResourceVerification;
    /**
     * 
     * @type {MemberProfileResourceWalletBalance}
     * @memberof MemberProfileResource
     */
    walletBalance: MemberProfileResourceWalletBalance;
}

/**
 * Check if a given object implements the MemberProfileResource interface.
 */
export function instanceOfMemberProfileResource(value: object): value is MemberProfileResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('hasPassword' in value) || value['hasPassword'] === undefined) return false;
    if (!('profileImage' in value) || value['profileImage'] === undefined) return false;
    if (!('verification' in value) || value['verification'] === undefined) return false;
    if (!('walletBalance' in value) || value['walletBalance'] === undefined) return false;
    return true;
}

export function MemberProfileResourceFromJSON(json: any): MemberProfileResource {
    return MemberProfileResourceFromJSONTyped(json, false);
}

export function MemberProfileResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberProfileResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'email': json['email'],
        'phone': json['phone'],
        'hasPassword': json['has_password'],
        'profileImage': json['profile_image'],
        'verification': MemberProfileResourceVerificationFromJSON(json['verification']),
        'walletBalance': MemberProfileResourceWalletBalanceFromJSON(json['wallet_balance']),
    };
}

export function MemberProfileResourceToJSON(json: any): MemberProfileResource {
    return MemberProfileResourceToJSONTyped(json, false);
}

export function MemberProfileResourceToJSONTyped(value?: MemberProfileResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'email': value['email'],
        'phone': value['phone'],
        'has_password': value['hasPassword'],
        'profile_image': value['profileImage'],
        'verification': MemberProfileResourceVerificationToJSON(value['verification']),
        'wallet_balance': MemberProfileResourceWalletBalanceToJSON(value['walletBalance']),
    };
}

