/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberResource } from './MemberResource';
import {
    MemberResourceFromJSON,
    MemberResourceFromJSONTyped,
    MemberResourceToJSON,
    MemberResourceToJSONTyped,
} from './MemberResource';

/**
 * 
 * @export
 * @interface MembersShow200ResponseData
 */
export interface MembersShow200ResponseData {
    /**
     * 
     * @type {MemberResource}
     * @memberof MembersShow200ResponseData
     */
    member: MemberResource;
}

/**
 * Check if a given object implements the MembersShow200ResponseData interface.
 */
export function instanceOfMembersShow200ResponseData(value: object): value is MembersShow200ResponseData {
    if (!('member' in value) || value['member'] === undefined) return false;
    return true;
}

export function MembersShow200ResponseDataFromJSON(json: any): MembersShow200ResponseData {
    return MembersShow200ResponseDataFromJSONTyped(json, false);
}

export function MembersShow200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MembersShow200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'member': MemberResourceFromJSON(json['member']),
    };
}

export function MembersShow200ResponseDataToJSON(json: any): MembersShow200ResponseData {
    return MembersShow200ResponseDataToJSONTyped(json, false);
}

export function MembersShow200ResponseDataToJSONTyped(value?: MembersShow200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MemberResourceToJSON(value['member']),
    };
}

