/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MyWalletResource
 */
export interface MyWalletResource {
    /**
     * 
     * @type {string}
     * @memberof MyWalletResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MyWalletResource
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof MyWalletResource
     */
    slug: string;
    /**
     * 
     * @type {number}
     * @memberof MyWalletResource
     */
    balance: number;
}

/**
 * Check if a given object implements the MyWalletResource interface.
 */
export function instanceOfMyWalletResource(value: object): value is MyWalletResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    return true;
}

export function MyWalletResourceFromJSON(json: any): MyWalletResource {
    return MyWalletResourceFromJSONTyped(json, false);
}

export function MyWalletResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyWalletResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'balance': json['balance'],
    };
}

export function MyWalletResourceToJSON(json: any): MyWalletResource {
    return MyWalletResourceToJSONTyped(json, false);
}

export function MyWalletResourceToJSONTyped(value?: MyWalletResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'balance': value['balance'],
    };
}

