/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationPagination } from './NotificationPagination';
import {
    NotificationPaginationFromJSON,
    NotificationPaginationFromJSONTyped,
    NotificationPaginationToJSON,
    NotificationPaginationToJSONTyped,
} from './NotificationPagination';
import type { NotificationResource } from './NotificationResource';
import {
    NotificationResourceFromJSON,
    NotificationResourceFromJSONTyped,
    NotificationResourceToJSON,
    NotificationResourceToJSONTyped,
} from './NotificationResource';

/**
 * 
 * @export
 * @interface NotificationsIndex200ResponseData
 */
export interface NotificationsIndex200ResponseData {
    /**
     * 
     * @type {Array<NotificationResource>}
     * @memberof NotificationsIndex200ResponseData
     */
    notifications: Array<NotificationResource>;
    /**
     * 
     * @type {NotificationPagination}
     * @memberof NotificationsIndex200ResponseData
     */
    pagination: NotificationPagination;
}

/**
 * Check if a given object implements the NotificationsIndex200ResponseData interface.
 */
export function instanceOfNotificationsIndex200ResponseData(value: object): value is NotificationsIndex200ResponseData {
    if (!('notifications' in value) || value['notifications'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function NotificationsIndex200ResponseDataFromJSON(json: any): NotificationsIndex200ResponseData {
    return NotificationsIndex200ResponseDataFromJSONTyped(json, false);
}

export function NotificationsIndex200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationsIndex200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'notifications': ((json['notifications'] as Array<any>).map(NotificationResourceFromJSON)),
        'pagination': NotificationPaginationFromJSON(json['pagination']),
    };
}

export function NotificationsIndex200ResponseDataToJSON(json: any): NotificationsIndex200ResponseData {
    return NotificationsIndex200ResponseDataToJSONTyped(json, false);
}

export function NotificationsIndex200ResponseDataToJSONTyped(value?: NotificationsIndex200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'notifications': ((value['notifications'] as Array<any>).map(NotificationResourceToJSON)),
        'pagination': NotificationPaginationToJSON(value['pagination']),
    };
}
