/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationResource } from './NotificationResource';
import {
    NotificationResourceFromJSON,
    NotificationResourceFromJSONTyped,
    NotificationResourceToJSON,
    NotificationResourceToJSONTyped,
} from './NotificationResource';

/**
 * 
 * @export
 * @interface NotificationsIndex200Response
 */
export interface NotificationsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<NotificationResource>}
     * @memberof NotificationsIndex200Response
     */
    data: Array<NotificationResource>;
}

/**
 * Check if a given object implements the NotificationsIndex200Response interface.
 */
export function instanceOfNotificationsIndex200Response(value: object): value is NotificationsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NotificationsIndex200ResponseFromJSON(json: any): NotificationsIndex200Response {
    return NotificationsIndex200ResponseFromJSONTyped(json, false);
}

export function NotificationsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(NotificationResourceFromJSON)),
    };
}

export function NotificationsIndex200ResponseToJSON(json: any): NotificationsIndex200Response {
    return NotificationsIndex200ResponseToJSONTyped(json, false);
}

export function NotificationsIndex200ResponseToJSONTyped(value?: NotificationsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(NotificationResourceToJSON)),
    };
}

