/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationResource
 */
export interface NotificationResource {
    /**
     * 
     * @type {number}
     * @memberof NotificationResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationResource
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResource
     */
    body: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationResource
     */
    isRead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof NotificationResource
     */
    createdAt: Date;
    /**
     * Type of action (e.g: listing_created, new_message, etc.)
     * @type {NotificationResourceActionTypeEnum}
     * @memberof NotificationResource
     */
    actionType: NotificationResourceActionTypeEnum;
    /**
     * ID of the related resource (e.g: listing id)
     * @type {number}
     * @memberof NotificationResource
     */
    actionId?: number | null;
}


/**
 * @export
 */
export const NotificationResourceActionTypeEnum = {
    ListingCreated: 'listing_created',
    NewMessage: 'new_message',
    ReviewReceived: 'review_received',
    SubscriptionExpired: 'subscription_expired',
    BoostApproved: 'boost_approved'
} as const;
export type NotificationResourceActionTypeEnum = typeof NotificationResourceActionTypeEnum[keyof typeof NotificationResourceActionTypeEnum];


/**
 * Check if a given object implements the NotificationResource interface.
 */
export function instanceOfNotificationResource(value: object): value is NotificationResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('actionType' in value) || value['actionType'] === undefined) return false;
    return true;
}

export function NotificationResourceFromJSON(json: any): NotificationResource {
    return NotificationResourceFromJSONTyped(json, false);
}

export function NotificationResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'body': json['body'],
        'isRead': json['is_read'],
        'createdAt': (new Date(json['created_at'])),
        'actionType': json['action_type'],
        'actionId': json['action_id'] == null ? undefined : json['action_id'],
    };
}

export function NotificationResourceToJSON(json: any): NotificationResource {
    return NotificationResourceToJSONTyped(json, false);
}

export function NotificationResourceToJSONTyped(value?: NotificationResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'body': value['body'],
        'is_read': value['isRead'],
        'created_at': value['createdAt'].toISOString(),
        'action_type': value['actionType'],
        'action_id': value['actionId'],
    };
}

