/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationResource
 */
export interface NotificationResource {
    /**
     * 
     * @type {number}
     * @memberof NotificationResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof NotificationResource
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof NotificationResource
     */
    body: string;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationResource
     */
    isRead: boolean;
    /**
     * 
     * @type {string}
     * @memberof NotificationResource
     */
    icon: string | null;
    /**
     * 
     * @type {string}
     * @memberof NotificationResource
     */
    referenceType: string;
    /**
     * 
     * @type {number}
     * @memberof NotificationResource
     */
    referenceId: number | null;
    /**
     * 
     * @type {Date}
     * @memberof NotificationResource
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the NotificationResource interface.
 */
export function instanceOfNotificationResource(value: object): value is NotificationResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('icon' in value) || value['icon'] === undefined) return false;
    if (!('referenceType' in value) || value['referenceType'] === undefined) return false;
    if (!('referenceId' in value) || value['referenceId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function NotificationResourceFromJSON(json: any): NotificationResource {
    return NotificationResourceFromJSONTyped(json, false);
}

export function NotificationResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'body': json['body'],
        'isRead': json['is_read'],
        'icon': json['icon'],
        'referenceType': json['reference_type'],
        'referenceId': json['reference_id'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function NotificationResourceToJSON(json: any): NotificationResource {
    return NotificationResourceToJSONTyped(json, false);
}

export function NotificationResourceToJSONTyped(value?: NotificationResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'body': value['body'],
        'is_read': value['isRead'],
        'icon': value['icon'],
        'reference_type': value['referenceType'],
        'reference_id': value['referenceId'],
        'created_at': value['createdAt'].toISOString(),
    };
}
