/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    currentPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    from?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    lastPage: number;
    /**
     * 
     * @type {string}
     * @memberof PaginationMeta
     */
    path?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    perPage: number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    to?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaginationMeta
     */
    total: number;
}

/**
 * Check if a given object implements the PaginationMeta interface.
 */
export function instanceOfPaginationMeta(value: object): value is PaginationMeta {
    if (!('currentPage' in value) || value['currentPage'] === undefined) return false;
    if (!('lastPage' in value) || value['lastPage'] === undefined) return false;
    if (!('perPage' in value) || value['perPage'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PaginationMetaFromJSON(json: any): PaginationMeta {
    return PaginationMetaFromJSONTyped(json, false);
}

export function PaginationMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPage': json['current_page'],
        'from': json['from'] == null ? undefined : json['from'],
        'lastPage': json['last_page'],
        'path': json['path'] == null ? undefined : json['path'],
        'perPage': json['per_page'],
        'to': json['to'] == null ? undefined : json['to'],
        'total': json['total'],
    };
}

export function PaginationMetaToJSON(json: any): PaginationMeta {
    return PaginationMetaToJSONTyped(json, false);
}

export function PaginationMetaToJSONTyped(value?: PaginationMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_page': value['currentPage'],
        'from': value['from'],
        'last_page': value['lastPage'],
        'path': value['path'],
        'per_page': value['perPage'],
        'to': value['to'],
        'total': value['total'],
    };
}

