/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginateMyListingPagination } from './PaginateMyListingPagination';
import {
    PaginateMyListingPaginationFromJSON,
    PaginateMyListingPaginationFromJSONTyped,
    PaginateMyListingPaginationToJSON,
    PaginateMyListingPaginationToJSONTyped,
} from './PaginateMyListingPagination';
import type { MyListingResource } from './MyListingResource';
import {
    MyListingResourceFromJSON,
    MyListingResourceFromJSONTyped,
    MyListingResourceToJSON,
    MyListingResourceToJSONTyped,
} from './MyListingResource';

/**
 * 
 * @export
 * @interface PaginateMyListing
 */
export interface PaginateMyListing {
    /**
     * 
     * @type {Array<MyListingResource>}
     * @memberof PaginateMyListing
     */
    listing: Array<MyListingResource>;
    /**
     * 
     * @type {PaginateMyListingPagination}
     * @memberof PaginateMyListing
     */
    pagination: PaginateMyListingPagination;
}

/**
 * Check if a given object implements the PaginateMyListing interface.
 */
export function instanceOfPaginateMyListing(value: object): value is PaginateMyListing {
    if (!('listing' in value) || value['listing'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginateMyListingFromJSON(json: any): PaginateMyListing {
    return PaginateMyListingFromJSONTyped(json, false);
}

export function PaginateMyListingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginateMyListing {
    if (json == null) {
        return json;
    }
    return {
        
        'listing': ((json['listing'] as Array<any>).map(MyListingResourceFromJSON)),
        'pagination': PaginateMyListingPaginationFromJSON(json['pagination']),
    };
}

export function PaginateMyListingToJSON(json: any): PaginateMyListing {
    return PaginateMyListingToJSONTyped(json, false);
}

export function PaginateMyListingToJSONTyped(value?: PaginateMyListing | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listing': ((value['listing'] as Array<any>).map(MyListingResourceToJSON)),
        'pagination': PaginateMyListingPaginationToJSON(value['pagination']),
    };
}

