/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface PasswordResetRequestResetOtp403Response
 */
export interface PasswordResetRequestResetOtp403Response {
    /**
     * 
     * @type {boolean}
     * @memberof PasswordResetRequestResetOtp403Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof PasswordResetRequestResetOtp403Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
}

/**
 * Check if a given object implements the PasswordResetRequestResetOtp403Response interface.
 */
export function instanceOfPasswordResetRequestResetOtp403Response(value: object): value is PasswordResetRequestResetOtp403Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PasswordResetRequestResetOtp403ResponseFromJSON(json: any): PasswordResetRequestResetOtp403Response {
    return PasswordResetRequestResetOtp403ResponseFromJSONTyped(json, false);
}

export function PasswordResetRequestResetOtp403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetRequestResetOtp403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
    };
}

export function PasswordResetRequestResetOtp403ResponseToJSON(json: any): PasswordResetRequestResetOtp403Response {
    return PasswordResetRequestResetOtp403ResponseToJSONTyped(json, false);
}

export function PasswordResetRequestResetOtp403ResponseToJSONTyped(value?: PasswordResetRequestResetOtp403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
    };
}

