/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetStoreNewPassword403Response
 */
export interface PasswordResetStoreNewPassword403Response {
    /**
     * 
     * @type {boolean}
     * @memberof PasswordResetStoreNewPassword403Response
     */
    success: boolean;
    /**
     * 
     * @type {PasswordResetStoreNewPassword403ResponseMessageEnum}
     * @memberof PasswordResetStoreNewPassword403Response
     */
    message: PasswordResetStoreNewPassword403ResponseMessageEnum;
}


/**
 * @export
 */
export const PasswordResetStoreNewPassword403ResponseMessageEnum = {
    Unauthorized: 'Unauthorized'
} as const;
export type PasswordResetStoreNewPassword403ResponseMessageEnum = typeof PasswordResetStoreNewPassword403ResponseMessageEnum[keyof typeof PasswordResetStoreNewPassword403ResponseMessageEnum];


/**
 * Check if a given object implements the PasswordResetStoreNewPassword403Response interface.
 */
export function instanceOfPasswordResetStoreNewPassword403Response(value: object): value is PasswordResetStoreNewPassword403Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function PasswordResetStoreNewPassword403ResponseFromJSON(json: any): PasswordResetStoreNewPassword403Response {
    return PasswordResetStoreNewPassword403ResponseFromJSONTyped(json, false);
}

export function PasswordResetStoreNewPassword403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetStoreNewPassword403Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function PasswordResetStoreNewPassword403ResponseToJSON(json: any): PasswordResetStoreNewPassword403Response {
    return PasswordResetStoreNewPassword403ResponseToJSONTyped(json, false);
}

export function PasswordResetStoreNewPassword403ResponseToJSONTyped(value?: PasswordResetStoreNewPassword403Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
    };
}

