/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetVerifyReset200ResponseData
 */
export interface PasswordResetVerifyReset200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetVerifyReset200ResponseData
     */
    resetToken: string;
}

/**
 * Check if a given object implements the PasswordResetVerifyReset200ResponseData interface.
 */
export function instanceOfPasswordResetVerifyReset200ResponseData(value: object): value is PasswordResetVerifyReset200ResponseData {
    if (!('resetToken' in value) || value['resetToken'] === undefined) return false;
    return true;
}

export function PasswordResetVerifyReset200ResponseDataFromJSON(json: any): PasswordResetVerifyReset200ResponseData {
    return PasswordResetVerifyReset200ResponseDataFromJSONTyped(json, false);
}

export function PasswordResetVerifyReset200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetVerifyReset200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'resetToken': json['reset_token'],
    };
}

export function PasswordResetVerifyReset200ResponseDataToJSON(json: any): PasswordResetVerifyReset200ResponseData {
    return PasswordResetVerifyReset200ResponseDataToJSONTyped(json, false);
}

export function PasswordResetVerifyReset200ResponseDataToJSONTyped(value?: PasswordResetVerifyReset200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reset_token': value['resetToken'],
    };
}

