/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetRequestResetOtpRequest
 */
export interface PasswordResetRequestResetOtpRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetRequestResetOtpRequest
     */
    phone: string;
}

/**
 * Check if a given object implements the PasswordResetRequestResetOtpRequest interface.
 */
export function instanceOfPasswordResetRequestResetOtpRequest(value: object): value is PasswordResetRequestResetOtpRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function PasswordResetRequestResetOtpRequestFromJSON(json: any): PasswordResetRequestResetOtpRequest {
    return PasswordResetRequestResetOtpRequestFromJSONTyped(json, false);
}

export function PasswordResetRequestResetOtpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetRequestResetOtpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
    };
}

export function PasswordResetRequestResetOtpRequestToJSON(json: any): PasswordResetRequestResetOtpRequest {
    return PasswordResetRequestResetOtpRequestToJSONTyped(json, false);
}

export function PasswordResetRequestResetOtpRequestToJSONTyped(value?: PasswordResetRequestResetOtpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
    };
}

