/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetStoreNewPasswordRequest
 */
export interface PasswordResetStoreNewPasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetStoreNewPasswordRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetStoreNewPasswordRequest
     */
    passwordConfirmation: string;
}

/**
 * Check if a given object implements the PasswordResetStoreNewPasswordRequest interface.
 */
export function instanceOfPasswordResetStoreNewPasswordRequest(value: object): value is PasswordResetStoreNewPasswordRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('passwordConfirmation' in value) || value['passwordConfirmation'] === undefined) return false;
    return true;
}

export function PasswordResetStoreNewPasswordRequestFromJSON(json: any): PasswordResetStoreNewPasswordRequest {
    return PasswordResetStoreNewPasswordRequestFromJSONTyped(json, false);
}

export function PasswordResetStoreNewPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetStoreNewPasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'passwordConfirmation': json['password_confirmation'],
    };
}

export function PasswordResetStoreNewPasswordRequestToJSON(json: any): PasswordResetStoreNewPasswordRequest {
    return PasswordResetStoreNewPasswordRequestToJSONTyped(json, false);
}

export function PasswordResetStoreNewPasswordRequestToJSONTyped(value?: PasswordResetStoreNewPasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'password_confirmation': value['passwordConfirmation'],
    };
}

