/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';
import type { PasswordResetVerifyReset200ResponseData } from './PasswordResetVerifyReset200ResponseData';
import {
    PasswordResetVerifyReset200ResponseDataFromJSON,
    PasswordResetVerifyReset200ResponseDataFromJSONTyped,
    PasswordResetVerifyReset200ResponseDataToJSON,
    PasswordResetVerifyReset200ResponseDataToJSONTyped,
} from './PasswordResetVerifyReset200ResponseData';

/**
 * 
 * @export
 * @interface PasswordResetVerifyReset200Response
 */
export interface PasswordResetVerifyReset200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PasswordResetVerifyReset200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof PasswordResetVerifyReset200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {PasswordResetVerifyReset200ResponseData}
     * @memberof PasswordResetVerifyReset200Response
     */
    data: PasswordResetVerifyReset200ResponseData;
}

/**
 * Check if a given object implements the PasswordResetVerifyReset200Response interface.
 */
export function instanceOfPasswordResetVerifyReset200Response(value: object): value is PasswordResetVerifyReset200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PasswordResetVerifyReset200ResponseFromJSON(json: any): PasswordResetVerifyReset200Response {
    return PasswordResetVerifyReset200ResponseFromJSONTyped(json, false);
}

export function PasswordResetVerifyReset200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetVerifyReset200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'data': PasswordResetVerifyReset200ResponseDataFromJSON(json['data']),
    };
}

export function PasswordResetVerifyReset200ResponseToJSON(json: any): PasswordResetVerifyReset200Response {
    return PasswordResetVerifyReset200ResponseToJSONTyped(json, false);
}

export function PasswordResetVerifyReset200ResponseToJSONTyped(value?: PasswordResetVerifyReset200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'data': PasswordResetVerifyReset200ResponseDataToJSON(value['data']),
    };
}

