/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';
import type { AuthRequestOtp200ResponseData } from './AuthRequestOtp200ResponseData';
import {
    AuthRequestOtp200ResponseDataFromJSON,
    AuthRequestOtp200ResponseDataFromJSONTyped,
    AuthRequestOtp200ResponseDataToJSON,
    AuthRequestOtp200ResponseDataToJSONTyped,
} from './AuthRequestOtp200ResponseData';

/**
 * 
 * @export
 * @interface PasswordResetRequestResetOtp200Response
 */
export interface PasswordResetRequestResetOtp200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PasswordResetRequestResetOtp200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof PasswordResetRequestResetOtp200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {AuthRequestOtp200ResponseData}
     * @memberof PasswordResetRequestResetOtp200Response
     */
    data: AuthRequestOtp200ResponseData;
}

/**
 * Check if a given object implements the PasswordResetRequestResetOtp200Response interface.
 */
export function instanceOfPasswordResetRequestResetOtp200Response(value: object): value is PasswordResetRequestResetOtp200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PasswordResetRequestResetOtp200ResponseFromJSON(json: any): PasswordResetRequestResetOtp200Response {
    return PasswordResetRequestResetOtp200ResponseFromJSONTyped(json, false);
}

export function PasswordResetRequestResetOtp200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetRequestResetOtp200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'data': AuthRequestOtp200ResponseDataFromJSON(json['data']),
    };
}

export function PasswordResetRequestResetOtp200ResponseToJSON(json: any): PasswordResetRequestResetOtp200Response {
    return PasswordResetRequestResetOtp200ResponseToJSONTyped(json, false);
}

export function PasswordResetRequestResetOtp200ResponseToJSONTyped(value?: PasswordResetRequestResetOtp200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'data': AuthRequestOtp200ResponseDataToJSON(value['data']),
    };
}

