/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentsStoreRequest
 */
export interface PaymentsStoreRequest {
    /**
     * 
     * @type {number}
     * @memberof PaymentsStoreRequest
     */
    amount: number;
    /**
     * 
     * @type {PaymentsStoreRequestMethodEnum}
     * @memberof PaymentsStoreRequest
     */
    method: PaymentsStoreRequestMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentsStoreRequest
     */
    transactionReference?: string | null;
}


/**
 * @export
 */
export const PaymentsStoreRequestMethodEnum = {
    Cib: 'CIB',
    BaridiMob: 'BaridiMob',
    Edahabia: 'Edahabia',
    BandMob: 'BandMob',
    External: 'External'
} as const;
export type PaymentsStoreRequestMethodEnum = typeof PaymentsStoreRequestMethodEnum[keyof typeof PaymentsStoreRequestMethodEnum];


/**
 * Check if a given object implements the PaymentsStoreRequest interface.
 */
export function instanceOfPaymentsStoreRequest(value: object): value is PaymentsStoreRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function PaymentsStoreRequestFromJSON(json: any): PaymentsStoreRequest {
    return PaymentsStoreRequestFromJSONTyped(json, false);
}

export function PaymentsStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentsStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'method': json['method'],
        'transactionReference': json['transaction_reference'] == null ? undefined : json['transaction_reference'],
    };
}

export function PaymentsStoreRequestToJSON(json: any): PaymentsStoreRequest {
    return PaymentsStoreRequestToJSONTyped(json, false);
}

export function PaymentsStoreRequestToJSONTyped(value?: PaymentsStoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'method': value['method'],
        'transaction_reference': value['transactionReference'],
    };
}

