/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentResource
 */
export interface PaymentResource {
    /**
     * 
     * @type {number}
     * @memberof PaymentResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentResource
     */
    transactionReference?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentResource
     */
    amount: number;
    /**
     * enum(CIB, BaridiMob, Edahabia, BandMob, External)
     * @type {string}
     * @memberof PaymentResource
     */
    method: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentResource
     */
    completed?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentResource
     */
    failed?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PaymentResource
     */
    createdAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PaymentResource
     */
    memberId: number;
}

/**
 * Check if a given object implements the PaymentResource interface.
 */
export function instanceOfPaymentResource(value: object): value is PaymentResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    return true;
}

export function PaymentResourceFromJSON(json: any): PaymentResource {
    return PaymentResourceFromJSONTyped(json, false);
}

export function PaymentResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'transactionReference': json['transaction_reference'] == null ? undefined : json['transaction_reference'],
        'amount': json['amount'],
        'method': json['method'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'createdAt': (json['created_at'] == null ? null : new Date(json['created_at'])),
        'memberId': json['member_id'],
    };
}

export function PaymentResourceToJSON(json: any): PaymentResource {
    return PaymentResourceToJSONTyped(json, false);
}

export function PaymentResourceToJSONTyped(value?: PaymentResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'transaction_reference': value['transactionReference'],
        'amount': value['amount'],
        'method': value['method'],
        'completed': value['completed'],
        'failed': value['failed'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'member_id': value['memberId'],
    };
}

