/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentsIndex200ResponseData } from './PaymentsIndex200ResponseData';
import {
    PaymentsIndex200ResponseDataFromJSON,
    PaymentsIndex200ResponseDataFromJSONTyped,
    PaymentsIndex200ResponseDataToJSON,
    PaymentsIndex200ResponseDataToJSONTyped,
} from './PaymentsIndex200ResponseData';

/**
 * 
 * @export
 * @interface PaymentsIndex200Response
 */
export interface PaymentsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PaymentsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {PaymentsIndex200ResponseData}
     * @memberof PaymentsIndex200Response
     */
    data: PaymentsIndex200ResponseData;
}

/**
 * Check if a given object implements the PaymentsIndex200Response interface.
 */
export function instanceOfPaymentsIndex200Response(value: object): value is PaymentsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaymentsIndex200ResponseFromJSON(json: any): PaymentsIndex200Response {
    return PaymentsIndex200ResponseFromJSONTyped(json, false);
}

export function PaymentsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PaymentsIndex200ResponseDataFromJSON(json['data']),
    };
}

export function PaymentsIndex200ResponseToJSON(json: any): PaymentsIndex200Response {
    return PaymentsIndex200ResponseToJSONTyped(json, false);
}

export function PaymentsIndex200ResponseToJSONTyped(value?: PaymentsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PaymentsIndex200ResponseDataToJSON(value['data']),
    };
}

