/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { PaymentResource } from './PaymentResource';
import {
    PaymentResourceFromJSON,
    PaymentResourceFromJSONTyped,
    PaymentResourceToJSON,
    PaymentResourceToJSONTyped,
} from './PaymentResource';

/**
 * 
 * @export
 * @interface PaymentsIndex200ResponseData
 */
export interface PaymentsIndex200ResponseData {
    /**
     * 
     * @type {Array<PaymentResource>}
     * @memberof PaymentsIndex200ResponseData
     */
    payments: Array<PaymentResource>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaymentsIndex200ResponseData
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaymentsIndex200ResponseData interface.
 */
export function instanceOfPaymentsIndex200ResponseData(value: object): value is PaymentsIndex200ResponseData {
    if (!('payments' in value) || value['payments'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaymentsIndex200ResponseDataFromJSON(json: any): PaymentsIndex200ResponseData {
    return PaymentsIndex200ResponseDataFromJSONTyped(json, false);
}

export function PaymentsIndex200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentsIndex200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'payments': ((json['payments'] as Array<any>).map(PaymentResourceFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaymentsIndex200ResponseDataToJSON(json: any): PaymentsIndex200ResponseData {
    return PaymentsIndex200ResponseDataToJSONTyped(json, false);
}

export function PaymentsIndex200ResponseDataToJSONTyped(value?: PaymentsIndex200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payments': ((value['payments'] as Array<any>).map(PaymentResourceToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

