/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentResource } from './PaymentResource';
import {
    PaymentResourceFromJSON,
    PaymentResourceFromJSONTyped,
    PaymentResourceToJSON,
    PaymentResourceToJSONTyped,
} from './PaymentResource';

/**
 * 
 * @export
 * @interface PaymentsStore201Response
 */
export interface PaymentsStore201Response {
    /**
     * 
     * @type {boolean}
     * @memberof PaymentsStore201Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof PaymentsStore201Response
     */
    message: string;
    /**
     * 
     * @type {PaymentResource}
     * @memberof PaymentsStore201Response
     */
    data: PaymentResource;
}

/**
 * Check if a given object implements the PaymentsStore201Response interface.
 */
export function instanceOfPaymentsStore201Response(value: object): value is PaymentsStore201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaymentsStore201ResponseFromJSON(json: any): PaymentsStore201Response {
    return PaymentsStore201ResponseFromJSONTyped(json, false);
}

export function PaymentsStore201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentsStore201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'data': PaymentResourceFromJSON(json['data']),
    };
}

export function PaymentsStore201ResponseToJSON(json: any): PaymentsStore201Response {
    return PaymentsStore201ResponseToJSONTyped(json, false);
}

export function PaymentsStore201ResponseToJSONTyped(value?: PaymentsStore201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': PaymentResourceToJSON(value['data']),
    };
}

