/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberProfileResource } from './MemberProfileResource';
import {
    MemberProfileResourceFromJSON,
    MemberProfileResourceFromJSONTyped,
    MemberProfileResourceToJSON,
    MemberProfileResourceToJSONTyped,
} from './MemberProfileResource';

/**
 * 
 * @export
 * @interface ProfileShow200Response
 */
export interface ProfileShow200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ProfileShow200Response
     */
    success: boolean;
    /**
     * 
     * @type {MemberProfileResource}
     * @memberof ProfileShow200Response
     */
    data: MemberProfileResource;
}

/**
 * Check if a given object implements the ProfileShow200Response interface.
 */
export function instanceOfProfileShow200Response(value: object): value is ProfileShow200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ProfileShow200ResponseFromJSON(json: any): ProfileShow200Response {
    return ProfileShow200ResponseFromJSONTyped(json, false);
}

export function ProfileShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': MemberProfileResourceFromJSON(json['data']),
    };
}

export function ProfileShow200ResponseToJSON(json: any): ProfileShow200Response {
    return ProfileShow200ResponseToJSONTyped(json, false);
}

export function ProfileShow200ResponseToJSONTyped(value?: ProfileShow200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': MemberProfileResourceToJSON(value['data']),
    };
}

