/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';
import type { MemberProfileResource } from './MemberProfileResource';
import {
    MemberProfileResourceFromJSON,
    MemberProfileResourceFromJSONTyped,
    MemberProfileResourceToJSON,
    MemberProfileResourceToJSONTyped,
} from './MemberProfileResource';

/**
 * 
 * @export
 * @interface ProfileUpdate200Response
 */
export interface ProfileUpdate200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ProfileUpdate200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof ProfileUpdate200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {MemberProfileResource}
     * @memberof ProfileUpdate200Response
     */
    data: MemberProfileResource;
}

/**
 * Check if a given object implements the ProfileUpdate200Response interface.
 */
export function instanceOfProfileUpdate200Response(value: object): value is ProfileUpdate200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ProfileUpdate200ResponseFromJSON(json: any): ProfileUpdate200Response {
    return ProfileUpdate200ResponseFromJSONTyped(json, false);
}

export function ProfileUpdate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileUpdate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'data': MemberProfileResourceFromJSON(json['data']),
    };
}

export function ProfileUpdate200ResponseToJSON(json: any): ProfileUpdate200Response {
    return ProfileUpdate200ResponseToJSONTyped(json, false);
}

export function ProfileUpdate200ResponseToJSONTyped(value?: ProfileUpdate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'data': MemberProfileResourceToJSON(value['data']),
    };
}

