/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyMatchersStore201Response
 */
export interface PropertyMatchersStore201Response {
    /**
     * 
     * @type {boolean}
     * @memberof PropertyMatchersStore201Response
     */
    success?: boolean;
    /**
     * 
     * @type {object}
     * @memberof PropertyMatchersStore201Response
     */
    data?: object;
}

/**
 * Check if a given object implements the PropertyMatchersStore201Response interface.
 */
export function instanceOfPropertyMatchersStore201Response(value: object): value is PropertyMatchersStore201Response {
    return true;
}

export function PropertyMatchersStore201ResponseFromJSON(json: any): PropertyMatchersStore201Response {
    return PropertyMatchersStore201ResponseFromJSONTyped(json, false);
}

export function PropertyMatchersStore201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyMatchersStore201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function PropertyMatchersStore201ResponseToJSON(json: any): PropertyMatchersStore201Response {
    return PropertyMatchersStore201ResponseToJSONTyped(json, false);
}

export function PropertyMatchersStore201ResponseToJSONTyped(value?: PropertyMatchersStore201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
    };
}

