/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyMatchersStoreRequest
 */
export interface PropertyMatchersStoreRequest {
    /**
     * User-defined label for the matcher.
     * @type {string}
     * @memberof PropertyMatchersStoreRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    categoryId: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    cityId?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    wilayaId?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    minPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    maxPrice?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    minSurface?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    maxSurface?: number;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersStoreRequest
     */
    rooms?: number;
    /**
     * Channels to receive alerts.
     * @type {Array<PropertyMatchersStoreRequestNotifyViaEnum>}
     * @memberof PropertyMatchersStoreRequest
     */
    notifyVia?: Array<PropertyMatchersStoreRequestNotifyViaEnum>;
}


/**
 * @export
 */
export const PropertyMatchersStoreRequestNotifyViaEnum = {
    Email: 'email',
    Push: 'push',
    Whatsapp: 'whatsapp'
} as const;
export type PropertyMatchersStoreRequestNotifyViaEnum = typeof PropertyMatchersStoreRequestNotifyViaEnum[keyof typeof PropertyMatchersStoreRequestNotifyViaEnum];


/**
 * Check if a given object implements the PropertyMatchersStoreRequest interface.
 */
export function instanceOfPropertyMatchersStoreRequest(value: object): value is PropertyMatchersStoreRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    return true;
}

export function PropertyMatchersStoreRequestFromJSON(json: any): PropertyMatchersStoreRequest {
    return PropertyMatchersStoreRequestFromJSONTyped(json, false);
}

export function PropertyMatchersStoreRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyMatchersStoreRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'categoryId': json['category_id'],
        'cityId': json['city_id'] == null ? undefined : json['city_id'],
        'wilayaId': json['wilaya_id'] == null ? undefined : json['wilaya_id'],
        'minPrice': json['min_price'] == null ? undefined : json['min_price'],
        'maxPrice': json['max_price'] == null ? undefined : json['max_price'],
        'minSurface': json['min_surface'] == null ? undefined : json['min_surface'],
        'maxSurface': json['max_surface'] == null ? undefined : json['max_surface'],
        'rooms': json['rooms'] == null ? undefined : json['rooms'],
        'notifyVia': json['notify_via'] == null ? undefined : json['notify_via'],
    };
}

export function PropertyMatchersStoreRequestToJSON(json: any): PropertyMatchersStoreRequest {
    return PropertyMatchersStoreRequestToJSONTyped(json, false);
}

export function PropertyMatchersStoreRequestToJSONTyped(value?: PropertyMatchersStoreRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'category_id': value['categoryId'],
        'city_id': value['cityId'],
        'wilaya_id': value['wilayaId'],
        'min_price': value['minPrice'],
        'max_price': value['maxPrice'],
        'min_surface': value['minSurface'],
        'max_surface': value['maxSurface'],
        'rooms': value['rooms'],
        'notify_via': value['notifyVia'],
    };
}

