/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PropertyMatchersIndex200Response
 */
export interface PropertyMatchersIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof PropertyMatchersIndex200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PropertyMatchersIndex200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof PropertyMatchersIndex200Response
     */
    status?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof PropertyMatchersIndex200Response
     */
    data?: Array<object>;
}

/**
 * Check if a given object implements the PropertyMatchersIndex200Response interface.
 */
export function instanceOfPropertyMatchersIndex200Response(value: object): value is PropertyMatchersIndex200Response {
    return true;
}

export function PropertyMatchersIndex200ResponseFromJSON(json: any): PropertyMatchersIndex200Response {
    return PropertyMatchersIndex200ResponseFromJSONTyped(json, false);
}

export function PropertyMatchersIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PropertyMatchersIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function PropertyMatchersIndex200ResponseToJSON(json: any): PropertyMatchersIndex200Response {
    return PropertyMatchersIndex200ResponseToJSONTyped(json, false);
}

export function PropertyMatchersIndex200ResponseToJSONTyped(value?: PropertyMatchersIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'status': value['status'],
        'data': value['data'],
    };
}

