/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';


/**
 * 
 * @export
 * @interface ReportsStore200Response
 */
export interface ReportsStore200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ReportsStore200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReportsStore200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof ReportsStore200Response
     */
    status?: number;
    /**
     * 
     * @type {null}
     * @memberof ReportsStore200Response
     */
    data?: null;
}

/**
 * Check if a given object implements the ReportsStore200Response interface.
 */
export function instanceOfReportsStore200Response(value: object): value is ReportsStore200Response {
    return true;
}

export function ReportsStore200ResponseFromJSON(json: any): ReportsStore200Response {
    return ReportsStore200ResponseFromJSONTyped(json, false);
}

export function ReportsStore200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportsStore200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : null
    };
}

export function ReportsStore200ResponseToJSON(json: any): ReportsStore200Response {
    return ReportsStore200ResponseToJSONTyped(json, false);
}

export function ReportsStore200ResponseToJSONTyped(value?: ReportsStore200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'status': value['status'],
        'data': null
    };
}

