/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestResource
 */
export interface RequestResource {
    /**
     * 
     * @type {number}
     * @memberof RequestResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof RequestResource
     */
    status?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RequestResource
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the RequestResource interface.
 */
export function instanceOfRequestResource(value: object): value is RequestResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function RequestResourceFromJSON(json: any): RequestResource {
    return RequestResourceFromJSONTyped(json, false);
}

export function RequestResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function RequestResourceToJSON(json: any): RequestResource {
    return RequestResourceToJSONTyped(json, false);
}

export function RequestResourceToJSONTyped(value?: RequestResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

