/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestResource } from './RequestResource';
import {
    RequestResourceFromJSON,
    RequestResourceFromJSONTyped,
    RequestResourceToJSON,
    RequestResourceToJSONTyped,
} from './RequestResource';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface RequestsStore201Response
 */
export interface RequestsStore201Response {
    /**
     * 
     * @type {boolean}
     * @memberof RequestsStore201Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof RequestsStore201Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {RequestResource}
     * @memberof RequestsStore201Response
     */
    data: RequestResource;
}

/**
 * Check if a given object implements the RequestsStore201Response interface.
 */
export function instanceOfRequestsStore201Response(value: object): value is RequestsStore201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RequestsStore201ResponseFromJSON(json: any): RequestsStore201Response {
    return RequestsStore201ResponseFromJSONTyped(json, false);
}

export function RequestsStore201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsStore201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'data': RequestResourceFromJSON(json['data']),
    };
}

export function RequestsStore201ResponseToJSON(json: any): RequestsStore201Response {
    return RequestsStore201ResponseToJSONTyped(json, false);
}

export function RequestsStore201ResponseToJSONTyped(value?: RequestsStore201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'data': RequestResourceToJSON(value['data']),
    };
}

