/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListingResource } from './ListingResource';
import {
    ListingResourceFromJSON,
    ListingResourceFromJSONTyped,
    ListingResourceToJSON,
    ListingResourceToJSONTyped,
} from './ListingResource';
import type { AuthRequestOtp403ResponseMessage } from './AuthRequestOtp403ResponseMessage';
import {
    AuthRequestOtp403ResponseMessageFromJSON,
    AuthRequestOtp403ResponseMessageFromJSONTyped,
    AuthRequestOtp403ResponseMessageToJSON,
    AuthRequestOtp403ResponseMessageToJSONTyped,
} from './AuthRequestOtp403ResponseMessage';

/**
 * 
 * @export
 * @interface Show200Response
 */
export interface Show200Response {
    /**
     * 
     * @type {boolean}
     * @memberof Show200Response
     */
    success: boolean;
    /**
     * 
     * @type {AuthRequestOtp403ResponseMessage}
     * @memberof Show200Response
     */
    message: AuthRequestOtp403ResponseMessage | null;
    /**
     * 
     * @type {ListingResource}
     * @memberof Show200Response
     */
    data: ListingResource;
}

/**
 * Check if a given object implements the Show200Response interface.
 */
export function instanceOfShow200Response(value: object): value is Show200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function Show200ResponseFromJSON(json: any): Show200Response {
    return Show200ResponseFromJSONTyped(json, false);
}

export function Show200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Show200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': AuthRequestOtp403ResponseMessageFromJSON(json['message']),
        'data': ListingResourceFromJSON(json['data']),
    };
}

export function Show200ResponseToJSON(json: any): Show200Response {
    return Show200ResponseToJSONTyped(json, false);
}

export function Show200ResponseToJSONTyped(value?: Show200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': AuthRequestOtp403ResponseMessageToJSON(value['message']),
        'data': ListingResourceToJSON(value['data']),
    };
}

