/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreRequestRequest
 */
export interface StoreRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof StoreRequestRequest
     */
    message?: string | null;
    /**
     * 
     * @type {number}
     * @memberof StoreRequestRequest
     */
    listingId?: number | null;
}

/**
 * Check if a given object implements the StoreRequestRequest interface.
 */
export function instanceOfStoreRequestRequest(value: object): value is StoreRequestRequest {
    return true;
}

export function StoreRequestRequestFromJSON(json: any): StoreRequestRequest {
    return StoreRequestRequestFromJSONTyped(json, false);
}

export function StoreRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'listingId': json['listing_id'] == null ? undefined : json['listing_id'],
    };
}

export function StoreRequestRequestToJSON(json: any): StoreRequestRequest {
    return StoreRequestRequestToJSONTyped(json, false);
}

export function StoreRequestRequestToJSONTyped(value?: StoreRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'listing_id': value['listingId'],
    };
}

