/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionsChargilyWebhookRequest
 */
export interface SubscriptionsChargilyWebhookRequest {
    /**
     * 
     * @type {SubscriptionsChargilyWebhookRequestTypeEnum}
     * @memberof SubscriptionsChargilyWebhookRequest
     */
    type: SubscriptionsChargilyWebhookRequestTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof SubscriptionsChargilyWebhookRequest
     */
    data: object;
}


/**
 * @export
 */
export const SubscriptionsChargilyWebhookRequestTypeEnum = {
    CheckoutPaid: 'checkout.paid',
    CheckoutFailed: 'checkout.failed',
    CheckoutExpired: 'checkout.expired'
} as const;
export type SubscriptionsChargilyWebhookRequestTypeEnum = typeof SubscriptionsChargilyWebhookRequestTypeEnum[keyof typeof SubscriptionsChargilyWebhookRequestTypeEnum];


/**
 * Check if a given object implements the SubscriptionsChargilyWebhookRequest interface.
 */
export function instanceOfSubscriptionsChargilyWebhookRequest(value: object): value is SubscriptionsChargilyWebhookRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SubscriptionsChargilyWebhookRequestFromJSON(json: any): SubscriptionsChargilyWebhookRequest {
    return SubscriptionsChargilyWebhookRequestFromJSONTyped(json, false);
}

export function SubscriptionsChargilyWebhookRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionsChargilyWebhookRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'data': json['data'],
    };
}

export function SubscriptionsChargilyWebhookRequestToJSON(json: any): SubscriptionsChargilyWebhookRequest {
    return SubscriptionsChargilyWebhookRequestToJSONTyped(json, false);
}

export function SubscriptionsChargilyWebhookRequestToJSONTyped(value?: SubscriptionsChargilyWebhookRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'data': value['data'],
    };
}

