/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionPlanResource
 */
export interface SubscriptionPlanResource {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionPlanResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPlanResource
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionPlanResource
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionPlanResource
     */
    durationDays: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionPlanResource
     */
    monthlyCoins: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionPlanResource
     */
    maxActiveListings: number;
    /**
     * List of features/limitations (e.g. 'Priority support', 'Boost listings', ...)
     * @type {Array<string>}
     * @memberof SubscriptionPlanResource
     */
    features?: Array<string>;
}

/**
 * Check if a given object implements the SubscriptionPlanResource interface.
 */
export function instanceOfSubscriptionPlanResource(value: object): value is SubscriptionPlanResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('durationDays' in value) || value['durationDays'] === undefined) return false;
    if (!('monthlyCoins' in value) || value['monthlyCoins'] === undefined) return false;
    if (!('maxActiveListings' in value) || value['maxActiveListings'] === undefined) return false;
    return true;
}

export function SubscriptionPlanResourceFromJSON(json: any): SubscriptionPlanResource {
    return SubscriptionPlanResourceFromJSONTyped(json, false);
}

export function SubscriptionPlanResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPlanResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'price': json['price'],
        'durationDays': json['duration_days'],
        'monthlyCoins': json['monthly_coins'],
        'maxActiveListings': json['max_active_listings'],
        'features': json['features'] == null ? undefined : json['features'],
    };
}

export function SubscriptionPlanResourceToJSON(json: any): SubscriptionPlanResource {
    return SubscriptionPlanResourceToJSONTyped(json, false);
}

export function SubscriptionPlanResourceToJSONTyped(value?: SubscriptionPlanResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'price': value['price'],
        'duration_days': value['durationDays'],
        'monthly_coins': value['monthlyCoins'],
        'max_active_listings': value['maxActiveListings'],
        'features': value['features'],
    };
}

