/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionResource
 */
export interface SubscriptionResource {
    /**
     * 
     * @type {number}
     * @memberof SubscriptionResource
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResource
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionResource
     */
    maxActiveListings: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionResource
     */
    monthlyCoins: number;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResource
     */
    transactionTypes?: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionResource
     */
    priorityLevel: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionResource
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionResource
     */
    durationDays: number;
}

/**
 * Check if a given object implements the SubscriptionResource interface.
 */
export function instanceOfSubscriptionResource(value: object): value is SubscriptionResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('maxActiveListings' in value) || value['maxActiveListings'] === undefined) return false;
    if (!('monthlyCoins' in value) || value['monthlyCoins'] === undefined) return false;
    if (!('priorityLevel' in value) || value['priorityLevel'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('durationDays' in value) || value['durationDays'] === undefined) return false;
    return true;
}

export function SubscriptionResourceFromJSON(json: any): SubscriptionResource {
    return SubscriptionResourceFromJSONTyped(json, false);
}

export function SubscriptionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'maxActiveListings': json['max_active_listings'],
        'monthlyCoins': json['monthly_coins'],
        'transactionTypes': json['transaction_types'] == null ? undefined : json['transaction_types'],
        'priorityLevel': json['priority_level'],
        'price': json['price'],
        'durationDays': json['duration_days'],
    };
}

export function SubscriptionResourceToJSON(json: any): SubscriptionResource {
    return SubscriptionResourceToJSONTyped(json, false);
}

export function SubscriptionResourceToJSONTyped(value?: SubscriptionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'max_active_listings': value['maxActiveListings'],
        'monthly_coins': value['monthlyCoins'],
        'transaction_types': value['transactionTypes'],
        'priority_level': value['priorityLevel'],
        'price': value['price'],
        'duration_days': value['durationDays'],
    };
}

