/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionsCheckout200ResponseData
 */
export interface SubscriptionsCheckout200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionsCheckout200ResponseData
     */
    checkoutUrl?: string;
}

/**
 * Check if a given object implements the SubscriptionsCheckout200ResponseData interface.
 */
export function instanceOfSubscriptionsCheckout200ResponseData(value: object): value is SubscriptionsCheckout200ResponseData {
    return true;
}

export function SubscriptionsCheckout200ResponseDataFromJSON(json: any): SubscriptionsCheckout200ResponseData {
    return SubscriptionsCheckout200ResponseDataFromJSONTyped(json, false);
}

export function SubscriptionsCheckout200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionsCheckout200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'checkoutUrl': json['checkout_url'] == null ? undefined : json['checkout_url'],
    };
}

export function SubscriptionsCheckout200ResponseDataToJSON(json: any): SubscriptionsCheckout200ResponseData {
    return SubscriptionsCheckout200ResponseDataToJSONTyped(json, false);
}

export function SubscriptionsCheckout200ResponseDataToJSONTyped(value?: SubscriptionsCheckout200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'checkout_url': value['checkoutUrl'],
    };
}

