/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionsCheckout200ResponseData } from './SubscriptionsCheckout200ResponseData';
import {
    SubscriptionsCheckout200ResponseDataFromJSON,
    SubscriptionsCheckout200ResponseDataFromJSONTyped,
    SubscriptionsCheckout200ResponseDataToJSON,
    SubscriptionsCheckout200ResponseDataToJSONTyped,
} from './SubscriptionsCheckout200ResponseData';

/**
 * 
 * @export
 * @interface SubscriptionsCheckout200Response
 */
export interface SubscriptionsCheckout200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionsCheckout200Response
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionsCheckout200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionsCheckout200Response
     */
    status?: number;
    /**
     * 
     * @type {SubscriptionsCheckout200ResponseData}
     * @memberof SubscriptionsCheckout200Response
     */
    data?: SubscriptionsCheckout200ResponseData;
}

/**
 * Check if a given object implements the SubscriptionsCheckout200Response interface.
 */
export function instanceOfSubscriptionsCheckout200Response(value: object): value is SubscriptionsCheckout200Response {
    return true;
}

export function SubscriptionsCheckout200ResponseFromJSON(json: any): SubscriptionsCheckout200Response {
    return SubscriptionsCheckout200ResponseFromJSONTyped(json, false);
}

export function SubscriptionsCheckout200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionsCheckout200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
        'data': json['data'] == null ? undefined : SubscriptionsCheckout200ResponseDataFromJSON(json['data']),
    };
}

export function SubscriptionsCheckout200ResponseToJSON(json: any): SubscriptionsCheckout200Response {
    return SubscriptionsCheckout200ResponseToJSONTyped(json, false);
}

export function SubscriptionsCheckout200ResponseToJSONTyped(value?: SubscriptionsCheckout200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'status': value['status'],
        'data': SubscriptionsCheckout200ResponseDataToJSON(value['data']),
    };
}

