/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionsCheckoutRequest
 */
export interface SubscriptionsCheckoutRequest {
    /**
     * ID of the subscription plan
     * @type {number}
     * @memberof SubscriptionsCheckoutRequest
     */
    planId: number;
    /**
     * 
     * @type {SubscriptionsCheckoutRequestPaymentMethodEnum}
     * @memberof SubscriptionsCheckoutRequest
     */
    paymentMethod: SubscriptionsCheckoutRequestPaymentMethodEnum;
}


/**
 * @export
 */
export const SubscriptionsCheckoutRequestPaymentMethodEnum = {
    Chargily: 'chargily',
    BankTransfer: 'bank_transfer'
} as const;
export type SubscriptionsCheckoutRequestPaymentMethodEnum = typeof SubscriptionsCheckoutRequestPaymentMethodEnum[keyof typeof SubscriptionsCheckoutRequestPaymentMethodEnum];


/**
 * Check if a given object implements the SubscriptionsCheckoutRequest interface.
 */
export function instanceOfSubscriptionsCheckoutRequest(value: object): value is SubscriptionsCheckoutRequest {
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    return true;
}

export function SubscriptionsCheckoutRequestFromJSON(json: any): SubscriptionsCheckoutRequest {
    return SubscriptionsCheckoutRequestFromJSONTyped(json, false);
}

export function SubscriptionsCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionsCheckoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'planId': json['plan_id'],
        'paymentMethod': json['payment_method'],
    };
}

export function SubscriptionsCheckoutRequestToJSON(json: any): SubscriptionsCheckoutRequest {
    return SubscriptionsCheckoutRequestToJSONTyped(json, false);
}

export function SubscriptionsCheckoutRequestToJSONTyped(value?: SubscriptionsCheckoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plan_id': value['planId'],
        'payment_method': value['paymentMethod'],
    };
}

