/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPlanResource } from './SubscriptionPlanResource';
import {
    SubscriptionPlanResourceFromJSON,
    SubscriptionPlanResourceFromJSONTyped,
    SubscriptionPlanResourceToJSON,
    SubscriptionPlanResourceToJSONTyped,
} from './SubscriptionPlanResource';

/**
 * 
 * @export
 * @interface SubscriptionsIndex200Response
 */
export interface SubscriptionsIndex200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionsIndex200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<SubscriptionPlanResource>}
     * @memberof SubscriptionsIndex200Response
     */
    data: Array<SubscriptionPlanResource>;
}

/**
 * Check if a given object implements the SubscriptionsIndex200Response interface.
 */
export function instanceOfSubscriptionsIndex200Response(value: object): value is SubscriptionsIndex200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SubscriptionsIndex200ResponseFromJSON(json: any): SubscriptionsIndex200Response {
    return SubscriptionsIndex200ResponseFromJSONTyped(json, false);
}

export function SubscriptionsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(SubscriptionPlanResourceFromJSON)),
    };
}

export function SubscriptionsIndex200ResponseToJSON(json: any): SubscriptionsIndex200Response {
    return SubscriptionsIndex200ResponseToJSONTyped(json, false);
}

export function SubscriptionsIndex200ResponseToJSONTyped(value?: SubscriptionsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(SubscriptionPlanResourceToJSON)),
    };
}

