/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSubscriptionResource } from './UserSubscriptionResource';
import {
    UserSubscriptionResourceFromJSON,
    UserSubscriptionResourceFromJSONTyped,
    UserSubscriptionResourceToJSON,
    UserSubscriptionResourceToJSONTyped,
} from './UserSubscriptionResource';

/**
 * 
 * @export
 * @interface SubscriptionsCurrent200Response
 */
export interface SubscriptionsCurrent200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionsCurrent200Response
     */
    success: boolean;
    /**
     * 
     * @type {UserSubscriptionResource}
     * @memberof SubscriptionsCurrent200Response
     */
    data: UserSubscriptionResource;
}

/**
 * Check if a given object implements the SubscriptionsCurrent200Response interface.
 */
export function instanceOfSubscriptionsCurrent200Response(value: object): value is SubscriptionsCurrent200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SubscriptionsCurrent200ResponseFromJSON(json: any): SubscriptionsCurrent200Response {
    return SubscriptionsCurrent200ResponseFromJSONTyped(json, false);
}

export function SubscriptionsCurrent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionsCurrent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': UserSubscriptionResourceFromJSON(json['data']),
    };
}

export function SubscriptionsCurrent200ResponseToJSON(json: any): SubscriptionsCurrent200Response {
    return SubscriptionsCurrent200ResponseToJSONTyped(json, false);
}

export function SubscriptionsCurrent200ResponseToJSONTyped(value?: SubscriptionsCurrent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UserSubscriptionResourceToJSON(value['data']),
    };
}

