/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionResource
 */
export interface TransactionResource {
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    type: string;
    /**
     * deposit or withdraw
     * @type {number}
     * @memberof TransactionResource
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    confirmed: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    reason: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    paymentMethod: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    paymentId: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    listingId: string | null;
    /**
     * 
     * @type {string}
     * @memberof TransactionResource
     */
    date: string;
}

/**
 * Check if a given object implements the TransactionResource interface.
 */
export function instanceOfTransactionResource(value: object): value is TransactionResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('confirmed' in value) || value['confirmed'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    if (!('listingId' in value) || value['listingId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function TransactionResourceFromJSON(json: any): TransactionResource {
    return TransactionResourceFromJSONTyped(json, false);
}

export function TransactionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'amount': json['amount'],
        'confirmed': json['confirmed'],
        'reason': json['reason'],
        'paymentMethod': json['payment_method'],
        'paymentId': json['payment_id'],
        'listingId': json['listing_id'],
        'date': json['date'],
    };
}

export function TransactionResourceToJSON(json: any): TransactionResource {
    return TransactionResourceToJSONTyped(json, false);
}

export function TransactionResourceToJSONTyped(value?: TransactionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'amount': value['amount'],
        'confirmed': value['confirmed'],
        'reason': value['reason'],
        'payment_method': value['paymentMethod'],
        'payment_id': value['paymentId'],
        'listing_id': value['listingId'],
        'date': value['date'],
    };
}

