/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRequestRequest
 */
export interface UpdateRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateRequestRequest
     */
    status?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateRequestRequest
     */
    message?: string | null;
}

/**
 * Check if a given object implements the UpdateRequestRequest interface.
 */
export function instanceOfUpdateRequestRequest(value: object): value is UpdateRequestRequest {
    return true;
}

export function UpdateRequestRequestFromJSON(json: any): UpdateRequestRequest {
    return UpdateRequestRequestFromJSONTyped(json, false);
}

export function UpdateRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function UpdateRequestRequestToJSON(json: any): UpdateRequestRequest {
    return UpdateRequestRequestToJSONTyped(json, false);
}

export function UpdateRequestRequestToJSONTyped(value?: UpdateRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

