/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionPlanResource } from './SubscriptionPlanResource';
import {
    SubscriptionPlanResourceFromJSON,
    SubscriptionPlanResourceFromJSONTyped,
    SubscriptionPlanResourceToJSON,
    SubscriptionPlanResourceToJSONTyped,
} from './SubscriptionPlanResource';

/**
 * 
 * @export
 * @interface UserSubscriptionResource
 */
export interface UserSubscriptionResource {
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionResource
     */
    id: number;
    /**
     * 
     * @type {SubscriptionPlanResource}
     * @memberof UserSubscriptionResource
     */
    plan: SubscriptionPlanResource;
    /**
     * 
     * @type {Date}
     * @memberof UserSubscriptionResource
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserSubscriptionResource
     */
    endDate?: Date;
    /**
     * 
     * @type {UserSubscriptionResourceStatusEnum}
     * @memberof UserSubscriptionResource
     */
    status: UserSubscriptionResourceStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionResource
     */
    remainingCoins?: number;
    /**
     * 
     * @type {number}
     * @memberof UserSubscriptionResource
     */
    activeListingsCount?: number;
}


/**
 * @export
 */
export const UserSubscriptionResourceStatusEnum = {
    Active: 'active',
    Expired: 'expired',
    Cancelled: 'cancelled'
} as const;
export type UserSubscriptionResourceStatusEnum = typeof UserSubscriptionResourceStatusEnum[keyof typeof UserSubscriptionResourceStatusEnum];


/**
 * Check if a given object implements the UserSubscriptionResource interface.
 */
export function instanceOfUserSubscriptionResource(value: object): value is UserSubscriptionResource {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('plan' in value) || value['plan'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UserSubscriptionResourceFromJSON(json: any): UserSubscriptionResource {
    return UserSubscriptionResourceFromJSONTyped(json, false);
}

export function UserSubscriptionResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSubscriptionResource {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'plan': SubscriptionPlanResourceFromJSON(json['plan']),
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'status': json['status'],
        'remainingCoins': json['remaining_coins'] == null ? undefined : json['remaining_coins'],
        'activeListingsCount': json['active_listings_count'] == null ? undefined : json['active_listings_count'],
    };
}

export function UserSubscriptionResourceToJSON(json: any): UserSubscriptionResource {
    return UserSubscriptionResourceToJSONTyped(json, false);
}

export function UserSubscriptionResourceToJSONTyped(value?: UserSubscriptionResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'plan': SubscriptionPlanResourceToJSON(value['plan']),
        'start_date': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString().substring(0,10),
        'end_date': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString().substring(0,10),
        'status': value['status'],
        'remaining_coins': value['remainingCoins'],
        'active_listings_count': value['activeListingsCount'],
    };
}

