/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionResource } from './TransactionResource';
import {
    TransactionResourceFromJSON,
    TransactionResourceFromJSONTyped,
    TransactionResourceToJSON,
    TransactionResourceToJSONTyped,
} from './TransactionResource';

/**
 * 
 * @export
 * @interface WalletTransactions200Response
 */
export interface WalletTransactions200Response {
    /**
     * 
     * @type {boolean}
     * @memberof WalletTransactions200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<TransactionResource>}
     * @memberof WalletTransactions200Response
     */
    data: Array<TransactionResource>;
}

/**
 * Check if a given object implements the WalletTransactions200Response interface.
 */
export function instanceOfWalletTransactions200Response(value: object): value is WalletTransactions200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WalletTransactions200ResponseFromJSON(json: any): WalletTransactions200Response {
    return WalletTransactions200ResponseFromJSONTyped(json, false);
}

export function WalletTransactions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletTransactions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(TransactionResourceFromJSON)),
    };
}

export function WalletTransactions200ResponseToJSON(json: any): WalletTransactions200Response {
    return WalletTransactions200ResponseToJSONTyped(json, false);
}

export function WalletTransactions200ResponseToJSONTyped(value?: WalletTransactions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(TransactionResourceToJSON)),
    };
}

