/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MyWalletResource } from './MyWalletResource';
import {
    MyWalletResourceFromJSON,
    MyWalletResourceFromJSONTyped,
    MyWalletResourceToJSON,
    MyWalletResourceToJSONTyped,
} from './MyWalletResource';
import type { TransactionResource } from './TransactionResource';
import {
    TransactionResourceFromJSON,
    TransactionResourceFromJSONTyped,
    TransactionResourceToJSON,
    TransactionResourceToJSONTyped,
} from './TransactionResource';

/**
 * 
 * @export
 * @interface WalletAddCoins200ResponseData
 */
export interface WalletAddCoins200ResponseData {
    /**
     * 
     * @type {MyWalletResource}
     * @memberof WalletAddCoins200ResponseData
     */
    wallet?: MyWalletResource;
    /**
     * 
     * @type {TransactionResource}
     * @memberof WalletAddCoins200ResponseData
     */
    transaction?: TransactionResource;
}

/**
 * Check if a given object implements the WalletAddCoins200ResponseData interface.
 */
export function instanceOfWalletAddCoins200ResponseData(value: object): value is WalletAddCoins200ResponseData {
    return true;
}

export function WalletAddCoins200ResponseDataFromJSON(json: any): WalletAddCoins200ResponseData {
    return WalletAddCoins200ResponseDataFromJSONTyped(json, false);
}

export function WalletAddCoins200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletAddCoins200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'wallet': json['wallet'] == null ? undefined : MyWalletResourceFromJSON(json['wallet']),
        'transaction': json['transaction'] == null ? undefined : TransactionResourceFromJSON(json['transaction']),
    };
}

export function WalletAddCoins200ResponseDataToJSON(json: any): WalletAddCoins200ResponseData {
    return WalletAddCoins200ResponseDataToJSONTyped(json, false);
}

export function WalletAddCoins200ResponseDataToJSONTyped(value?: WalletAddCoins200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'wallet': MyWalletResourceToJSON(value['wallet']),
        'transaction': TransactionResourceToJSON(value['transaction']),
    };
}

