/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WalletAddCoins200ResponseData } from './WalletAddCoins200ResponseData';
import {
    WalletAddCoins200ResponseDataFromJSON,
    WalletAddCoins200ResponseDataFromJSONTyped,
    WalletAddCoins200ResponseDataToJSON,
    WalletAddCoins200ResponseDataToJSONTyped,
} from './WalletAddCoins200ResponseData';

/**
 * 
 * @export
 * @interface WalletAddCoins200Response
 */
export interface WalletAddCoins200Response {
    /**
     * 
     * @type {boolean}
     * @memberof WalletAddCoins200Response
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof WalletAddCoins200Response
     */
    message: string;
    /**
     * 
     * @type {WalletAddCoins200ResponseData}
     * @memberof WalletAddCoins200Response
     */
    data: WalletAddCoins200ResponseData;
}

/**
 * Check if a given object implements the WalletAddCoins200Response interface.
 */
export function instanceOfWalletAddCoins200Response(value: object): value is WalletAddCoins200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WalletAddCoins200ResponseFromJSON(json: any): WalletAddCoins200Response {
    return WalletAddCoins200ResponseFromJSONTyped(json, false);
}

export function WalletAddCoins200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletAddCoins200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'data': WalletAddCoins200ResponseDataFromJSON(json['data']),
    };
}

export function WalletAddCoins200ResponseToJSON(json: any): WalletAddCoins200Response {
    return WalletAddCoins200ResponseToJSONTyped(json, false);
}

export function WalletAddCoins200ResponseToJSONTyped(value?: WalletAddCoins200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': WalletAddCoins200ResponseDataToJSON(value['data']),
    };
}

