/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MyWalletResource } from './MyWalletResource';
import {
    MyWalletResourceFromJSON,
    MyWalletResourceFromJSONTyped,
    MyWalletResourceToJSON,
    MyWalletResourceToJSONTyped,
} from './MyWalletResource';

/**
 * 
 * @export
 * @interface WalletShow200Response
 */
export interface WalletShow200Response {
    /**
     * 
     * @type {boolean}
     * @memberof WalletShow200Response
     */
    success: boolean;
    /**
     * 
     * @type {MyWalletResource}
     * @memberof WalletShow200Response
     */
    data: MyWalletResource;
}

/**
 * Check if a given object implements the WalletShow200Response interface.
 */
export function instanceOfWalletShow200Response(value: object): value is WalletShow200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WalletShow200ResponseFromJSON(json: any): WalletShow200Response {
    return WalletShow200ResponseFromJSONTyped(json, false);
}

export function WalletShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': MyWalletResourceFromJSON(json['data']),
    };
}

export function WalletShow200ResponseToJSON(json: any): WalletShow200Response {
    return WalletShow200ResponseToJSONTyped(json, false);
}

export function WalletShow200ResponseToJSONTyped(value?: WalletShow200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': MyWalletResourceToJSON(value['data']),
    };
}

