/* tslint:disable */
/* eslint-disable */
/**
 * Laravel
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WalletAddCoinsRequest
 */
export interface WalletAddCoinsRequest {
    /**
     * 
     * @type {number}
     * @memberof WalletAddCoinsRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof WalletAddCoinsRequest
     */
    reason: string;
    /**
     * 
     * @type {WalletAddCoinsRequestPaymentMethodEnum}
     * @memberof WalletAddCoinsRequest
     */
    paymentMethod?: WalletAddCoinsRequestPaymentMethodEnum | null;
}


/**
 * @export
 */
export const WalletAddCoinsRequestPaymentMethodEnum = {
    Chargily: 'chargily',
    BankTransfer: 'bank_transfer',
    Wallet: 'wallet'
} as const;
export type WalletAddCoinsRequestPaymentMethodEnum = typeof WalletAddCoinsRequestPaymentMethodEnum[keyof typeof WalletAddCoinsRequestPaymentMethodEnum];


/**
 * Check if a given object implements the WalletAddCoinsRequest interface.
 */
export function instanceOfWalletAddCoinsRequest(value: object): value is WalletAddCoinsRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function WalletAddCoinsRequestFromJSON(json: any): WalletAddCoinsRequest {
    return WalletAddCoinsRequestFromJSONTyped(json, false);
}

export function WalletAddCoinsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WalletAddCoinsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'reason': json['reason'],
        'paymentMethod': json['payment_method'] == null ? undefined : json['payment_method'],
    };
}

export function WalletAddCoinsRequestToJSON(json: any): WalletAddCoinsRequest {
    return WalletAddCoinsRequestToJSONTyped(json, false);
}

export function WalletAddCoinsRequestToJSONTyped(value?: WalletAddCoinsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'reason': value['reason'],
        'payment_method': value['paymentMethod'],
    };
}

